### ISSUE TITLE
Support of Norwegian languages (NOR, NOB, NNO)

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#1]
I experience the following issues with the support of Norwegian in this SDK.

- used a copy of TED schema and Schematron rules which makes all forms created with the main language of (NOR, NOB, NNO) invalid, see business rule BR-BT-00702-0102. Could you provide an extended schema and Schematron files?
- translation API (https://dof-notices-dev-api.azure-api.net/notices/translate) supports only language "NOR" as a main language, do you expect to support languages "NOB" and "NNO" as well?

**Comment by kjorlaug** [comment]
Hi - the first point is something we both should report to OP as it's a bug in the eForms implementation,

**Comment by kjorlaug** [comment]
On the second - please use doffin@dfo.no for this as it's related the Doffin implementation, not eForms. For your information NOR is the "umbrella" for NOB and NNO, it's not three distinct languages. In most cases NOR is synonym with NOB.
