### ISSUE TITLE
Submit API returns 201 (Created)

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#15]
Per your documentation (https://dof-notices-dev-api.developer.azure-api.net/api-details#api=eform-api&operation=post-submit-eform), it is expected to receive code 200 on successful submission, see the screenshot below.
However, I am getting code 201. Is it expected behavior? Would you change your documentation or API implementation?

![image](https://github.com/anskaffelser/eforms-sdk-nor/assets/59865467/ae34dee4-767a-4fc6-8f1b-6c111c6e810b)

**Comment by haroonalam16** [comment]
Thanks for your feedback. Expected behavior is code 201 which you are getting. We will check it internally and will update the documentation accordingly.
