### ISSUE TITLE
Notice of subtype 1 complains about ContractFolderId

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#16]
A notice with id "70dae2db-28db-4cab-baa2-d9fb00db9688" of subtype 1 has been validated and submitted on dof-notices-dev-api.azure-api.net

Now I am polling for notice status (https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/search-esentool?id={0}&versionId={1}) and getting following result, see below.

A "procedureId" property in response says about missing contract folder id.

What does it mean? How it could be missing if TED stands for a field BT-04-notice "ContractFolderID" being forbidden for subtypes [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "T01", "X01", "X02" ]

`{
	"totalSize": 1,
	"content": [
		{
			"id": "70dae2db-28db-4cab-baa2-d9fb00db9688",
			"versionId": "01",
			"publicationId": null,
			"ngoj": null,
			"publicationDate": null,
			"procedureId": "ContractFolderID missing",
			"status": "SUBMITTED",
			"updatedAt": null,
			"submittedAt": "2023-09-07T17:45:33.087406+02:00",
			"noticeType": "1",
			"legalBasis": "32014L0024",
			"languages": [
				"NOR",
				"ENG"
			],
			"noticeAuthor": "publication-test@mercell.com"
		}
	]
}`

**Comment by kjorlaug** [comment]
Hi

We've looked into this, and you are completly right. We are rolling out a fix that will remove the message in the procedureId field. Seems like PO generates an UUID for the field in their search-result - are you using that or is it ok just to ignore the content for now?

--

Rune

**Comment by eduardsmirnov** [comment]
it is just a remark, I do not use it.

**Comment by haroonalam16** [comment]
We rolled out the fix and it resolved the mentioned issue for future submitted request.
