### ISSUE TITLE
Documentation for Submit API

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#17]
I would recommend clearly writing in documentation that you do not support an upload of an XML file in a standard way. API crashes when the header "Content-Disposition" of XML part contains a reference to the filename [Content-Disposition: form-data; name="notice"**; filename="name.xml"**]. It is not clear from your cURL example, see the screenshot below.

![image](https://github.com/anskaffelser/eforms-sdk-nor/assets/59865467/9cb53eb4-29c8-4d6f-b007-9c8e6fdc7449)

**Comment by eduardsmirnov** [comment]
Hi @sandrawiborg 
please see attached screenshot, text in bold.
When a file is attached with filename (seems to be standard for me), API is not working.
Without filename it works well.
Actually it should work with both variants.

![image](https://github.com/anskaffelser/eforms-sdk-nor/assets/59865467/3831445b-be72-4a8d-8ce2-8272415826d3)

**Comment by sandrawiborg** [comment]
I close this issue for now. Please let us know if this will be a problem when testing further.
