### ISSUE TITLE
Search API - request for new response parameter

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#18]
I see that Search API contains TED publication ID ("_publicationId_"). Could you also add the date of TED publication? Probably also TED publication status makes sense.

Do I understand right that existing TED publication Id means a notice is published on TED? In all other cases you will return any other non-published status?

Is it possible that Doffin will be published before TED? e.g. due to 48h rule
What will be the status in this case? Submitted or Published?
Our current logic will stop polling status as soon as we receive Published status.

**Comment by haroonalam16** [comment]
Hello,
Please find the answers to your questions below:

> _I see that Search API contains TED publication ID ("_publicationId_"). Could you also add the date of TED publication? Probably also TED publication status makes sense._

The idea was that we try to keep the API in line with TED it means the "status" field shows the TED publication status [SUBMITTED,  VALIDATION_FAILED, PUBLISHED etc] 

> _Do I understand right that existing TED publication Id means a notice is published on TED? In all other cases you will return any other non-published status?_

Yes, for notices that goes to TED ("TED notices" from now on) we follow the status from TED, with the only exception that we might have up to two hours delay from they update their status until we re-poll and update our status. This means that our status is the exact same as TED's status - only with up to two hours delay.

> _Is it possible that Doffin will be published before TED? e.g. due to 48h rule What will be the status in this case? Submitted or Published? Our current logic will stop polling status as soon as we receive Published status._

No, for TED notices this should not be possible as the thing that triggers publishing of TED notices at our side is a state change when we poll TED.


Regards
Erik and Haroon

**Comment by eduardsmirnov** [comment]
Today Doffin has implemented 48h rule. Would it be deprecated with a lunch of eForms?

**Comment by kjorlaug** [comment]
Yes - until further notice at least. It's not a rule, but a practice based on an interpetation of "confirmation of receipt" clause in the regulation. We plan to challenge PO on why this is not a state in the eNotices2 API, and based on how they answer we might change the internal logic in Doffin at a later stage.
