### ISSUE TITLE
Auto-translate of organization names

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#2]
Translation API (https://dof-notices-dev-api.azure-api.net/notices/translate) translates also organization names.
The translated result looks weird, e.g. "RETT BAD AS" translated to "STRAIGHT BAD AS" and "DOMENE KLUBBEN NR 282" translated to "DOMAIN CLUB NO. 282". Is it what you intended? 

Also for your information, Organization name fields (BT-500-Organization-Company and BT-500-Organization-TouchPoint) have xpathRelative "cac:PartyName/cbc:Name", not "cbc:Name", so to produce a correct translated XML you need to fix a path instead of XML like below 

`<efac:Company>
	<cac:PartyName>
	  <cbc:Name languageID="NOR">RETT BAD AS</cbc:Name>
	  <cbc:Name languageID="ENG">STRAIGHT BAD AS</cbc:Name>
	</cac:PartyName>
</efac:Company>`

you should produce XML like following

`<efac:Company>
	<cac:PartyName>
	  <cbc:Name languageID="NOR">RETT BAD AS</cbc:Name>
	</cac:PartyName>
	<cac:PartyName>
	  <cbc:Name languageID="ENG">STRAIGHT BAD AS</cbc:Name>
	</cac:PartyName>
</efac:Company>`

**Comment by haroonalam16** [comment]
Hello,
Sorry that this issue has not received an answer earlier. Yes we are aware of that "Auto-translation" service is not up to mark and has some known issues like you mentioned above. In the future we have plan to improve it at least for the known issues. 
Appreciate your suggestions and corrections for Organization Name files etc.

Regards,
Haroon

**Comment by sandrawiborg** [comment]
Reported in Jira: [DOF-1635](https://dfo-no.atlassian.net/browse/DOF-1635)

**Comment by kjorlaug** [comment]
The translate service has no logic related to content by design. You can either omit sending the names for translation, or you can override the result you get back.
