### ISSUE TITLE
Validation failed for national notice N4

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#20]
Latest SDK contains notice subtype N4.

An attempt to validate this notice via Doffin API https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/validate leads to the error "success:false".
What is wrong? Do you support lately released SDK?

File is attached.
[ES_subtype_N1_20230911-001.txt](https://github.com/anskaffelser/eforms-sdk-nor/files/12575238/ES_subtype_N1_20230911-001.txt)

**Comment by sandrawiborg** [comment]
Jira-task: DOF-1634 [https://dfo-no.atlassian.net/browse/DOF-1634](url)

**Comment by haroonalam16** [comment]
I would like to inform you that we have updated our system with latest e-form SDK (https://github.com/anskaffelser/eforms-sdk-nor/releases/tag/v20230914), with which national notice subtype N4 can be validated.

Can you please test N4 and confirm, Thanks.
