### ISSUE TITLE
Again cannot validate EU notice due to missing EU language

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#21]
With the latest Doffin SDK (https://github.com/anskaffelser/eforms-sdk-nor/releases/tag/v20230904), a new rule has been introduced which again does not allow us to perform an intermediate validation for EU notices.
EFORMS-NOR-R008
"Minimum one of the official languages must be provided"

Could you convert this rule into a warning?

Below is a comparison of file "eu-norway.xslt" between SDK versions.
![image](https://github.com/anskaffelser/eforms-sdk-nor/assets/59865467/e53ded0e-09d2-4d31-9257-141e7eead9e9)

**Comment by klakegg** [comment]
Fixed in https://github.com/anskaffelser/eforms-sdk-nor/commit/c5da0aad7c8f92baaf6103f354803e11fd790872
