### ISSUE TITLE
Error due to waiting for dispatch to TED too long

### ISSUE THREAD

**Issue by Anastassiabp** [anskaffelser/eforms-sdk-nor#22]
Hi!
The error was returned regarding the notice **650ad70a6a7b4c2ef155e903** 
It turned out that it was waiting for 6 days before dispatch to TED, which returned an error that the notice dispatch date must not be more than 24 hours before the current date. Can you propose the solution for this situation? Will notices be automatically resent from your side if it happens? Or should we change the version and dispatch the notice again - in this case is there any guarantee that the notice doesn't get stuck for several days again?

```
<svrl:failed-assert location="/cn:ContractNotice/cbc:IssueDate" test="((current-date() - xs:date(text())) le xs:dayTimeDuration('P2D')) and ((current-date() - xs:date(text())) ge xs:dayTimeDuration('-P1D'))" role="ERROR">
    <svrl:text>
		Notice Dispatch Date must be between 0 and 24 hours before the current date.
	</svrl:text>
  </svrl:failed-assert>
```

b95992d0-f17f-4e13-a82c-18e6e3e6c11d-01 business id

submitted 2023-09-20T15:33:58+03:00

ted failed 2023-09-26T12:21:26+03:00

**Comment by haroonalam16** [comment]
Hello,

Sorry for inconvenience. We had known issue to sending the Notice's to TED (https://github.com/anskaffelser/eforms-sdk-nor/issues/19) with which we were working. While testing the fix the notices we received during last couple of days were trigger towards TED. Though notices were valid but as it sent late from our side so it violate the Notice Dispatch date rule.

We are going to roll out the fix today so after that once we will receive the valid notice we will send immediately (poll every 5 minute). 

I am hoping in future this issue will not happen as soon as our system up and running. At the moment I can see two scenarios where it can happen; one if our system is down more then 24 our or TED system is down more the 24 hours. I am hoping that mentioned two scenarios will not happen but still we will consider them and come back with strategy to tackle such situations.


Best regards,
Haroon Alam

**Comment by haroonalam16** [comment]
Hello,

We have rolled out the fix to the issue you mentioned ( please check https://github.com/anskaffelser/eforms-sdk-nor/issues/19). EU (1, 16 etc) notices will be sent to TED within 5 minutes once we receive them. Sender will receive email directly from TED in both cases either Notices is SUBMITTED or VALIDATION_FAILED.

All National notices (N16, N29, N4) which are ready for publishing being prepared for publishing at 08:50 (status = PUBLISHING) and at 09:00 it published with status = PUBLISHED.

You can test both EU and National notices, If you encounter any issue please let us know. Thanks.

Regards,
Haroon

**Comment by sandrawiborg** [comment]
Hi @Anastassiabp 
I close this issue as it is solved. If you experience the error again, please let us know. 

All the best, 
Sandra
