### ISSUE TITLE
Notices API on Search

### ISSUE THREAD

**Issue by 577854** [anskaffelser/eforms-sdk-nor#25]
if issueDateFrom and IssueDateTo is formatted wrong (For example: "2023-10-05T00:00:00Z"), the api will return all notices. 
Correct format seems to be "yyyy-mm-dd" for the date parameters. 
It Would be helpful to show examples/formatting for parameters in api or give a failed response with error message. 
Not a crutial issue.

**Comment by sandrawiborg** [comment]
Hi @577854 
I appreciate the notice. We have added some examples in our API documentation, so I close this issue.
