### ISSUE TITLE
Some records make the API return 204

### ISSUE THREAD

**Issue by Hagroth** [anskaffelser/eforms-sdk-nor#26]
When searching, some records make the API return 204, despite there still being records after it, so it's not out of bounds. See e.g. https://betaapi.doffin.no/public/v2/search?numHitsPerPage=1&page=170 (also 171, and probably more).

**Comment by dsa-dfo** [comment]
Thank you for informing us of this issue. We have made a few changes since this issue was raised, are you still experiencing problems? I am not able to reproduce it at the moment.
