### ISSUE TITLE
Where can I view my test notices?

### ISSUE THREAD

**Issue by kayjohnsen** [anskaffelser/eforms-sdk-nor#29]
I have submitted test notices using your API endpoint https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/submit

Is there a website where I can see the result? Something simular to https://beta.doffin.no/search but for test environment?

This would be very helpful, to see the mapping between my XML values ​​and the final result on Doffin.

**Comment by kjorlaug** [comment]
Try https://dof-webclient-dev-app.azurewebsites.net/

**Comment by kayjohnsen** [comment]
Great!

Any idea why my notice is not showing here https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100512 ?

**Comment by sandrawiborg** [comment]
Hi @kayjohnsen 
We are currently converting old announcements. Please try again in 24 hours.

**Comment by kayjohnsen** [comment]
Dette er i testmiljøet, konverterer dere der også? Dette er ikke en gammel kunngjøring, men en kunngjøring levert på eForms formatet, konverterer dere disse også?

Jeg har i dag submitted en notice i testmiljøet med id "ff35cab3-8587-488a-9d56-1b52e072e76c". Den er nå søkbar med "Search notices" APIet, men den er ikke synlig på https://dof-webclient-dev-app.azurewebsites.net/. Når blir den synlig der?

**Comment by sandrawiborg** [comment]
Hei igjen. Vi er midt i lansering, men kommer tilbake til deg når vi har mulighet. Kan ta noe ekstra tid i disse dager pga lansering.

**Comment by kayjohnsen** [comment]
Det er greit, håper å høre fra dere inne mandag da vi er avhengig av svar fra dere for å komme videre med testingen.

**Comment by kjorlaug** [comment]
Er formen du har send inn eu eller national? Kan være den venter på push
til TED (som er nok stoppa).

Prøv ein nasjonal, dei bør gå gjennom og bli synlig i test

Mvh

Rune

tor. 12. okt. 2023, 16:40 skrev kayjohnsen ***@***.***>:

**Comment by haroonalam16** [comment]
Din notice med ID "ff35cab3-8587-488a-9d56-1b52e072e76c" er nasjonalt dokument (N16), som vil bli publisere i dag rundt kl. 09:10, etter det vil notice være synlig.

**Comment by kayjohnsen** [comment]
> Din notice med ID "ff35cab3-8587-488a-9d56-1b52e072e76c" er nasjonalt dokument (N16), som vil bli publisere i dag rundt kl. 09:10, etter det vil notice være synlig.

Flott, nå er den synlig på søkesiden, men hvorfor vises ikke detaljene her https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100534 ?

**Comment by haroonalam16** [comment]
Vi sjekker det, vi oppdaterer deg så snart vi får mer informasjon. Takk.

**Comment by kayjohnsen** [comment]
Har dere funnet ut noe mer om hvorfor detaljene om kunngjøringene mine ikke vises på test?

**Comment by CharlotteKolle** [comment]
Hei Kay - som jeg skrev i mailen for litt siden stemmer det at vi ikke har funksjonalitet i dev for å vise kunngjøringer der. Dette er ikke noe vi har hatt mulighet til å prioritere, og ikke noe vi ser at vi klarer å prioritere med det aller første heller. Vi har en aktiv eforms publisert på Doffin nå, så se gjerne på den som eksempel. https://www.doffin.no/notices/2023-100267

**Comment by kayjohnsen** [comment]
Forstår jeg det riktig som at dere ikke har et fungerende testmiljø? Hvordan skal vi teste da? Hvordan har dere testet frem til nå?

**Comment by kayjohnsen** [comment]
Jeg tror vi snakker forbi hverandre @CharlotteKolle for dere har vitterlig et testmiljø her https://dof-webclient-dev-app.azurewebsites.net/search

Mitt spørsmål gjelder de fire kunngjøringene jeg har postet her https://dof-webclient-dev-app.azurewebsites.net/search?page=1&type=ANNOUNCEMENT_OF_COMPETITION&searchString=milj%C3%B8direktoratet

Når jeg klikker inn på dem https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100603 så får jeg "Kunngjøring ikke funnet". 

Så mitt spørsmål er hvorfor jeg får "Kunngjøring ikke funnet", for jeg vil jo gjerne se detaljene til de kunngjøringene jeg har postet. 

Jeg ser jo at andre får til dette https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100626 (Artifik), så kanskje det er noe feil i mine notices?

Dette må det være mulig for dere å svare på @haroonalam16 @kjorlaug @sandrawiborg ? Vi kommer ikke videre i vår testing før dette svares ut.

**Comment by haroonalam16** [comment]
Hei Kay,
Du kan se din kunngjøringen med doffinid 2023-100603 på webclient: 

https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100603

Dessverre er ikke de andre kunngjøringene dine synlige ennå men jeg fant problemet, så jeg må teste litt mer. Jeg skal oppdatere deg om det.

**Comment by haroonalam16** [comment]
Hei Igjen,

Nå alle kunngjøringer er synlige:
https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100603
https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100561
https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100534
https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100512

**Comment by sandrawiborg** [comment]
Hei @kayjohnsen 
Beklager at det har vært mye frem og tilbake i denne dialogen. Selve lanseringen av doffin.no har tatt en del fokus, men nå ser det ut til at denne saken med dine kunngjøringer er løst. Jeg lukker saken, så får du sende en kommentar om du er uenig. Håper dette hjelper dere videre i arbeidet med å teste.

**Comment by kayjohnsen** [comment]
Hei, det er supert at jeg nå kan se detaljer om mine tidligere innsendte kunngjøringer i testmiljøet.

I går onsdag 24. oktober sendte jeg en ny kunngjøring. Den er ennå ikke synlig. Hvorfor er den ikke synlig? Er det ikke automatikk knyttet til dette? Må jeg opprette en issue her for hver kunngjøringen jeg sender via APIet slik at dere manuelt kan trykke den igjennom? Fint hvis dere kunne utdypet litt rundt hvordan dette fungerer.

Jeg sendte også en kunngjøring i går som skal til TED. Den står med status "MANUAL_CHECK". Hva betyr det?

**Comment by haroonalam16** [comment]
Hei,
Alt skal fungere automatisk, og når du har sendt inn Notice, og det er publisert, vil det være synlig på nettet (doffin.no).
Notices du sendte tidligere, som ikke ble vist, ble PUBLISERT, men da vi prøvde å vise dem på nettet, ga det et problem på grunn av DateTime-problemet i vår side, som vi fikset.

"MANUAL_CHECK" er intern status som dukker opp bare når systemet får uventet feil for det Notice, så vi sjekker det manuelt.

**Comment by kayjohnsen** [comment]
Hei, presiserer at alle mine spørsmål gjelder TEST-miljøet.

Hvor lang tid skal det ta fra jeg sender en kunngjøring til den blir synlig her https://dof-webclient-dev-app.azurewebsites.net/search ?

Kunngjøringen jeg sendte inn i går har fått "ngoj" 2023-100664 og publicationDate i dag, så det betyr vel at den skulle vært synlig her https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100664 men det er den ikke. Vet dere hvorfor? 

Når får jeg svar på de to kunngjøringene mine som skal til TED og som har status "MANUAL_CHECK"?

**Comment by haroonalam16** [comment]
Hei igjen,

Når kunngjøringen er publisert, kan det være synlig for nettklienten innen 1-2 timer.
kan du gi meg eform ID til TED Notices?
jeg bare fant en 21ca1d28-811c-42d6-9934-cd2c54f2ec5c? Jeg skal sjekke det nå.

**Comment by haroonalam16** [comment]
Hei Igjen,
Lurer på er det mulig for deg å sende "Time" uten nano sekunder, e.g

i stedet for <cbc:IssueTime>15:46:44.6288824+02:00</cbc:IssueTime>
send <cbc:IssueTime>15:46:44+02:00</cbc:IssueTime>

i stedet for <efbc:TransmissionTime>15:46:44.6288824+02:00</efbc:TransmissionTime>
send <efbc:TransmissionTime>15:46:44+02:00</efbc:TransmissionTime>
Det gjelder for alle felter med "Time"

Hvis Ja kan du sende en Nasjonal kunngjøringen nå?

**Comment by kayjohnsen** [comment]
Hei igjen :)

Da sendte jeg en nasjonal kunngjøring hvor tidselementet er definert som du beskriver. Den fikk id lik "459f066f-ce5c-4411-98df-0313c17f4ad6".

**Comment by kayjohnsen** [comment]
> Hei igjen,
> 
> Når kunngjøringen er publisert, kan det være synlig for nettklienten innen 1-2 timer. kan du gi meg eform ID til TED Notices? jeg bare fant en 21ca1d28-811c-42d6-9934-cd2c54f2ec5c? Jeg skal sjekke det nå.

Jeg har også en annen med id "78fded58-e457-45e8-80b5-af4c60223c1f", men det er den siste med id "21ca1d28-811c-42d6-9934-cd2c54f2ec5c" som er viktigst da den er mest oppdatert.

**Comment by haroonalam16** [comment]
Perfekt, 459f066f-ce5c-4411-98df-0313c17f4ad6 er publisert nå (https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100665).
6fa57cd2-aa2f-42ed-9932-d5e3911d470e og 7c7c2005-4ba7-47ec-be59-972f06503533 publiseres i morgen tidlig rundt 0910

Kan du sende din TED Notices igjen med tidselementet som jeg skrevet oppe?

**Comment by kayjohnsen** [comment]
> Perfekt, 459f066f-ce5c-4411-98df-0313c17f4ad6 er publisert nå (https://dof-webclient-dev-app.azurewebsites.net/notices/2023-100665). 6fa57cd2-aa2f-42ed-9932-d5e3911d470e og 7c7c2005-4ba7-47ec-be59-972f06503533 publiseres i morgen tidlig rundt 0910
> 
> Kan du sende din TED Notices igjen med tidselementet som jeg skrevet oppe?

a7ab218c-6d67-4235-8adc-b55dd7faafb2

**Comment by haroonalam16** [comment]
Jeg kan se din eform 504ee8d5-f22a-4705-950a-5bb55f4cd8ee (type 16) har noen problemer med XML så TED godtar det ikke. Jeg skal prøve å sjekke XML i morgen.
Men kan du prøve å sende flere Notices til TED?

**Comment by sandrawiborg** [comment]
Hei @kayjohnsen 
Hvis dette fortsatt er et problem, har du mulighet til å sende flere notices til TED? Manuel_check er en status som genereres dersom filen ikke valideres hos TED. Årsaken er feil i XML, men ikke alltid så lett å oppdage hva/hvor. Vi prøver imidlertid å fikse dette fortløpende.

**Comment by kayjohnsen** [comment]
> Hei @kayjohnsen Hvis dette fortsatt er et problem, har du mulighet til å sende flere notices til TED? Manuel_check er en status som genereres dersom filen ikke valideres hos TED. Årsaken er feil i XML, men ikke alltid så lett å oppdage hva/hvor. Vi prøver imidlertid å fikse dette fortløpende.

3ea3b82a-ca88-4ed8-8134-0713b0dd83b5

**Comment by kayjohnsen** [comment]
Any news about my TED-notices? They all still have status "MANUAL_CHECK".

**Comment by kayjohnsen** [comment]
Er det noe utvikling rundt alle sakene med "MANUAL_CHECK" på TED-notices? Ser det er flere andre som etterlyser svar på dette også.

**Comment by haroonalam16** [comment]
Når vi prøver å SENDE kunngjøringen til TED, og TED ikke godtar den av en eller annen grunn, så merker vi den MANUAL_CHECK (som er en intern status for oss).

Vi jobber med å finne årsakene og løse dem, slik at det ikke skjer neste gang.
 
I TED Notices som du har sendt tidligere, har du brukt "Custom namespace" som TED ikke aksepterer.  Dette er et problem på TED sin side siden de har hardkodet det, og vi får dessverre ikke får gjort noe med så her må en rett og slett bruke samme namespaces som i de offisielle eksempelfilene fra TED: 

https://github.com/OP-TED/eForms-SDK/tree/develop/examples/notices
 
Kan du sende Noticen på nytt og passe på å bruke samme namespace som i eksempelfilene?

**Comment by kayjohnsen** [comment]
Jeg har nå endret namespace slik at namespace for rotelementet er default namespace. Jeg får fortsatt "MANUAL_CHECK" på mine to siste noticer "3836093d-0d29-479e-94bb-278461fc753f" og "e44366de-0a19-4076-bbc2-bc860eb9fa2e". Kan dere hjelpe meg videre @haroonalam16 ?

**Comment by kayjohnsen** [comment]
Noe nytt her @haroonalam16 ?

**Comment by haroonalam16** [comment]
Kan du prøve å sende inn på nytt e44366de-0a19-4076-bbc2-bc860eb9fa2e og 3836093d-0d29-479e-94bb-278461fc753f?
Jeg prøvde det selv og det gikk bra.

**Comment by haroonalam16** [comment]
Hei,
Ja, jeg ser Notisen a1863aae-c4ca-4853-acec-38ac4cfedf69 i systemet, men problemet å sendes til TED, selv om XML ser bra ut for meg.

kan du please prøve "noticeAuthorLocale" "en" i metadata i stedet for "no" og sende igjen notisen igjen med "noticeAuthorLocale": "en".

f.eks:
 metadata={ "noticeAuthorEmail": "john@doe.com","noticeAuthorLocale": "en" }

**Comment by haroonalam16** [comment]
Hei,
Jeg kan se at du har sendt ny Notisen 5bfb3fcf-f89b-4ae6-a3ae-384e4133bbed, som er sendt til TED, jeg tror du også har fått bekreftelses-e-post fra TED. Kan du bekrefte?

**Comment by haroonalam16** [comment]
Du kan prøve å sende flere Kunngjøringene (til TED), men i "noticeAuthorLocale": bruk et av EUs offisielle språk f.eks "en", ikke "no". For nasjonale Notisen er det ikke problemet.

**Comment by kayjohnsen** [comment]
Hei, da har jeg fått bekreftelse fra TED på notice "5bfb3fcf-f89b-4ae6-a3ae-384e4133bbed", så da var det nok "noticeAuthorLocale" som må være "en". Tusen takk for hjelpen @haroonalam16 :)
