### ISSUE TITLE
Cannot test API directly from test environment due to CORS issue

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#3]
Trying to test API at https://dof-notices-dev-api.developer.azure-api.net/api-details#api=eform-api&operation=post-submit-eform
Cannot do it in a browser due to following: 
`Unable to complete the request. Since the browser initiates the request, it requires Cross-Origin Resource Sharing (CORS) enabled on the server. `

Could you fix it to allow testing?

**Comment by sandrawiborg** [comment]
Hi @eduardsmirnov 
I´m trying to clean up a bit on our issues to make sure we prioritize to solve the ones that are still relevant. Is this issue still relevant or can I close it?

**Comment by eduardsmirnov** [comment]
Hi @sandrawiborg,
not sure if you tried to reproduce this issue.
This is a screenshot made today.
![image](https://github.com/anskaffelser/eforms-sdk-nor/assets/59865467/49a4a952-564f-414e-9b6e-e4e6231ca14a)

**Comment by sandrawiborg** [comment]
Hi @eduardsmirnov 
We looked at this issue again, and we now understand the issue. We put this in our backlog and will have a look at this after the launch period. Issue number is: [DOF-1794 ](https://dfo-no.atlassian.net/browse/DOF-1794)

**Comment by kjorlaug** [comment]
Sorry that this has dragged out a bit @eduardsmirnov. Not supporting CORS is a design choice as we don't want (at least for now) to open up our API's for webclient use, just machine to machine. As @sandrawiborg mentioned we've put this in the backlog for now and will re-assess the choice at a later stage.
