### ISSUE TITLE
Translate notice returnerer 500-feil

### ISSUE THREAD

**Issue by kayjohnsen** [anskaffelser/eforms-sdk-nor#30]
Dette gjelder testmiljøet.

Når jeg bruker eksempelet dere har her [https://dof-notices-dev-api.developer.azure-api.net/api-details#api=eform-api&operation=post-translate-eform] og poster til Translate APIet, så får jeg en 500-feil.

`<ProcurementProject>
    <Name languageID="NOR">Dette er en overskrift</Name>
    <Description languageID="NOR">Dette er enbeskrivelse</Description>
    <Note languageID="NOR">Dette er en note</Note>
    <cac:PartyName>
        <cbc:Name languageID="NOR">Egennavn</cbc:Name>
    </cac:PartyName>
</ProcurementProject>`

Hvis jeg fjerner `<ProcurementProject>` så fungerer det og jeg får en oversatt versjon tilbake. Hvorfor skjer denne feilen? Er ikke tanken at jeg kan sende inn en fullstendig notice-XML og få den tilbake igjen med oversatte tekster?

Hvis en kunngjøring skal til TED, ønsker dere at vi submitter en notice-XML med ferdige oversettelser, eller skal vi submitte en "norsk" versjon også får vi tilbake en oversatt versjon fra dere?

**Comment by kayjohnsen** [comment]
Hei, har dere funnet ut noe her?

**Comment by kjorlaug** [comment]
Only when you use the submit call to Doffin API (formally sending the notice for publication), not the translate call. The translate call has no validation or requirements to the content posted - it only looks for xml-tags with language attribiutes and tries to add a translation for them.
