### ISSUE TITLE
Endringskunngjøring with no reference to previous notice

### ISSUE THREAD

**Issue by 577854** [anskaffelser/eforms-sdk-nor#31]
I've noticed that the old form "F14" called "Endringskunngjøring" is translated to a "<Contractnotice>" of subtype "99" for eForms. In the old form, "F14", one coud see what changes were made and a reference to the changed notice with a doffinID reference. In the new eForms with subtype 99, there seems to be no trace of the old notice that was changed/updated. Is there a way to find a reference to the changed notice in the new eForms when it is a "Endringskunngjøring"?

**Comment by 577854** [comment]
Thank you for your answer :) 

I did find the cbc:URI tag referencing the classic doffin url, which should be enugh to parse and get the original DoffinID, but every eForms notice I've looked at only has the link "https://classic.doffin.no/Notice/Details/" as the value in cbc:URI.  Would it be possible to change the value to be the classic doffin url with the DoffinID? 

Also would the new eForms that havent been parsed from old notices have a different way of reffering to the changed notice and wpuld the subtype be different?

**Comment by erik-itland** [comment]
We are looking into this now and it is beeing tracked internally as DOF-1929.

**Comment by 577854** [comment]
One small question:
Will the new eForms notices (not historical) have the same doffinID as the old one, when there is a change to the old one?

An example would be a notice with doffinID "2023-1111" and a form type "Competition" and subtype "16", and then when a change/endring happens, a new notice is published with the same doffinID ("2023-1111") and subtype ("16") but with a form type "Change"

![image](https://github.com/anskaffelser/eforms-sdk-nor/assets/42579586/9f590ffa-4ea4-4fe3-894a-46a8b54ba950)

**Comment by sandrawiborg** [comment]
Hi Gudsteinn @577854 
The original notice and the change notice will have different Doffin-ID. 

You can see an example here, on a new e-form notice: 
Original notice: [https://www.doffin.no/notices/2023-100281]
Change notice: [https://www.doffin.no/notices/2023-100296]

The Notice identifier is the same, but with new version (02). The Reference/Doffin-ID is also new on the change notice. Hope this is an answer to your question.
