### ISSUE TITLE
Please help with API

### ISSUE THREAD

**Issue by david-law1** [anskaffelser/eforms-sdk-nor#33]
Hi,

We are calling the API daily but we are struggling to get the correct notices through.

We started by using this query(for the last 24 hours worth of notices) and it didn't pull through everything from that time period:

https://api.doffin.no/public/v2/search?issueDateFrom=2023-10-26T05:02:35

We updated the query to the below to include number of hits per page and it is ignoring the issue from and to dates and just pulling 200 notices each run.

https://api.doffin.no/public/v2/search?issueDateFrom=2023-10-26T05:00:37&issueDateTo=2023-10-27T05:00:37&numHitsPerPage=200

Can someone advise if this is a bug or are we missing something with our API call?

**Comment by haroonalam16** [comment]
Hello,
Sorry for inconvenience, we are checking the issue and update you as soon as possible.
Haroon

**Comment by haroonalam16** [comment]
Hi,
We have checked the issue, it seems when use time period with date it take as null, that is why it don't give you desired result. 
If you try the query with date (without time period) like mentioned in API documentation "Starting date in issue date range on format yyyy-mm-dd (from)" and "End date in issue date range on format yyyy-mm-dd (to)", it should work and give desired result.

More we will consider to extend API to support time period as well in near future. 

Haroon

**Comment by david-law1** [comment]
Hi,

We just tried this query:

https://api.doffin.no/public/v2/search?issueDateFrom=2023-10-27&issueDateTo=2023-10-30

And we are still getting just 15 notices.

**Comment by haroonalam16** [comment]
Hi,
We are checking the issue and we created the case to handle this issue: https://dfo-no.atlassian.net/browse/DOF-1990
we will update you as soon as possible.

**Comment by haroonalam16** [comment]
Hi,

Can you try it again with this query:
https://api.doffin.no/public/v2/search?issueDateFrom=2023-10-27&issueDateTo=2023-10-30
you should get "numHitsTotal": 143.

Please let me know if you get the correct results.

Within this thread you can find more info about Public API.

**Comment by david-law1** [comment]
We have tried this and it does have the correct number but this number is increasing as the week goes on with the same query. We are seeing notices being inserted with the publish date of the 31st that we haven't received through the API until the 3rd. For example:

https://doffin.no/notices/2023-100458 - published date of the 31st but we only got it through the API on the 3rd at 10.55am
https://doffin.no/notices/2023-100459 - published date of the 31st but we only got it through the API on the 3rd at 10.55am
https://doffin.no/notices/2023-100460 - published date of the 31st but we only got it through the API on the 3rd at 10.55am

is this correct?

**Comment by haroonalam16** [comment]
Good, that you are getting correct results now :)
Sorry I forget the link to thread I mentioned earlier, within this thread you can find more info about Public API search results: https://github.com/anskaffelser/eforms-sdk-nor/issues/35.

https://doffin.no/notices/2023-100458 submitted  on 31st Oct and Published on 3rd Nov
https://doffin.no/notices/2023-100459 submitted  on 31st Oct and Published on 3rd Nov
https://doffin.no/notices/2023-100460 submitted  on 31st Oct and Published on 3rd Nov

API only shows results with Notices "PUBLISHED" status, that is why mentioned Notices visible on 3rd Nov.

**Comment by david-law1** [comment]
Ah okay, I think I get you now. I thought the website was based on a published date rather than a submitted date so I got confused when 'new' notices were sitting much further down the list than expected.

Will all OJEU notices have this kind of delay between submitting and publishing?

**Comment by haroonalam16** [comment]
`Will all OJEU notices have this kind of delay between submitting and publishing?`
Yes, we depend on when TED PUBLISH the notice after submitting it to TED.
