### ISSUE TITLE
"MANUAL_CHECK" status 

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#34]
Hi!

We received the following response for the following call: https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/search-esentool?id=d6c5bc11-9833-4e82-9664-64581ddb61b5&versionId=01 in test.

Can we have some more information? Why has this notice been blocked for two weeks? What is expected from us in such as case?

{
    "totalSize": 1,
    "content": [
        {
            "id": "d6c5bc11-9833-4e82-9664-64581ddb61b5",
            "versionId": "01",
            "publicationId": null,
            "ngoj": null,
            "publicationDate": null,
            "procedureId": "8f8d3a3d-4b95-4ed1-b070-c10cdca65f6d",
            "status": "MANUAL_CHECK",
            "updatedAt": null,
            "submittedAt": "2023-10-12T15:55:16.177461+02:00",
            "noticeType": "36",
            "legalBasis": "32014L

**Comment by haroonalam16** [comment]
Hello,
Manuel_check is a status we marked if the file is not validated at TED. The reason can be a mistake in the XML or something else, but not always so easy to discover so why needs to manual check. However, we are trying to priorities and fix this on an ongoing basis. 

We will check d6c5bc11-9833-4e82-9664-64581ddb61b5 (type 36), and will update you if find any problem.  we have created  task to handle it: DOF-1988

**Comment by jlouvrier** [comment]
Hi! Thanks for your reply. 

@kjorlaug we would have preferred to be notified about this possible status before it is implemented. Now we discover something that we are not prepared for. 

Do I understand correctly that we should not react to this status and just keep pooling until you return a status published or error/rejected?

**Comment by kjorlaug** [comment]
I understand your concern @jlouvrier. Our test/dev enviornment will get some more attention again now that the production enviornment is stable. That said - as it is a test/dev environment there is always the chance of incositencies over the time.

To your question - once we have accepted the notice (through the submitNotice call) then it's our responsibilty. The MANUAL_CHECK status should not have been exposed to you, the correct status for you should have been SUBMITTED (we will fix that).

**Comment by jlouvrier** [comment]
Excellent, we are on the same page.
