### ISSUE TITLE
Stop notice publication - Business ID

### ISSUE THREAD

**Issue by agnelgonsal** [anskaffelser/eforms-sdk-nor#37]
Hi Doffin team,

We are currently working on the Stop Pulbication feature and not sure how to exactly use it. In the API URL, it expects us to pass something called as "Business ID"

https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/**{businessID}**/stop-publication-esentool

But we are not sure what it is? We tried sending the value we send in the <cbc:ID> tag while submitting the notice but we get 404 - Notice not found in response.

We call the search Notice API to see if such business ID value exists but could not find anything.

Could you please assist here and let us know what value should we pass as the Business ID in API call?

Thank you.

Kind Regards,
Agnel Gonsalves

**Comment by haroonalam16** [comment]
Hello,
Business ID is combination of eform id and versionID, "-" is combining them :
businessID = id-versionId 

<img width="709" alt="Skjermbilde 2023-11-07 133310" src="https://github.com/anskaffelser/eforms-sdk-nor/assets/91733674/2f59f5bc-0e45-42ba-ae45-b9bad044cf17">

When Notice successfully submitted to TED, Ted sent confirmation email with subject line e.g:

Your notice e8acb40a-5b46-4b6e-8d23-448a555d1234-01 is submitted.
e8acb40a-5b46-4b6e-8d23-448a555d1234-01 is businessID.

 so if I want to stop the notice  e8acb40a-5b46-4b6e-8d23-448a555d1234-01 then call would be like:
 
 https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/e8acb40a-5b46-4b6e-8d23-448a555d1234-01/stop-publication-esentool
 

Hoping it will help you.
