### ISSUE TITLE
(PROD) Cannot get status of Submitted notice

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#38]
Please check.

NoticeID: d0c196ce-ab7a-4426-a62e-fe2d77b81ed0
Subtype: N16

Submission started at: 2023-11-02T11:36:15.389Z
Response received at: 2023-11-02T11:37:50.289Z

```
StatusCode: 201, ReasonPhrase: 'Created', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:3afc27ce-bdf9-4d9c-9cff-4ee790a59947
Date: Thu, 02 Nov 2023 11:37:49 GMT
Content-Type: application/json; charset=utf-8
}
{
"success": true
}
```

Until now we try to get its status using API
https://api.doffin.no/api/v2/notice/notices/search-esentool?id=d0c196ce-ab7a-4426-a62e-fe2d77b81ed0&versionId=01

It returns back
```
{
    "totalSize": 0,
    "content": []
}
```

Do you see this notice in the system? Should we re-submit it?

**Comment by haroonalam16** [comment]
Hello,

I couldn't find any Notice with id 0c196ce-ab7a-4426-a62e-fe2d77b81ed0. It is strange that it submitted successfully but couldn't emerged in our system. we will check the logs to find out the reason.

But it's good to re-submit the notice d0c196ce-ab7a-4426-a62e-fe2d77b81ed0. 

Haroon

**Comment by jlouvrier** [comment]
Same issue with this notice 417a58b4-813b-4df3-bb50-59119e68569e submitted on Nov 02

**Comment by jlouvrier** [comment]
@haroonalam16 have you found anything in your logs? This would be important for us to understand what happened and how to prevent this from happening. I am afraid that it happened to multiple forms.

**Comment by kjorlaug** [comment]
We have found them in our system - trying to find out what has happended now.

**Comment by haroonalam16** [comment]
Hello,
We are working on the issue and already has good progress, can you guys please send the following again:

d0c196ce-ab7a-4426-a62e-fe2d77b81ed0
417a58b4-813b-4df3-bb50-59119e68569e 

Thanks in advance.

**Comment by haroonalam16** [comment]
Hello Eduard,

Can you please re-submit the Notices which has status MANUAL_CHECK? I can see couple of Notices with MANUAL_CHECK . If you want i can share the list of Notices with MANAUAL_CHECK status. Thanks.

**Comment by jlouvrier** [comment]
Please share the list asap

**Comment by haroonalam16** [comment]
Here are the list of eforms with "MANAUAL_CHECK" status sent by Mercell:

0097de15-36cf-4750-96c9-f66ae4d6cafd
11160cdd-6a1b-4741-a209-60f20ef5d02d
d99106c5-2389-418f-b193-c2624af82ab0
cc4f47b3-a154-441a-8e66-3bc78e180e56
70813649-84da-4617-b2c5-0ba961d35a36
0dda73e8-794e-4449-9ca2-c0a01357012c
016538f9-82da-48cc-9bfa-3c9edc1d9505
417b78fd-1a50-4501-ac6f-0fb29d9d13a4

Once you re-submit them, can you please let me know so we can follow them.

**Comment by haroonalam16** [comment]
It looks all notice you resubmitted to TED are sent to TED. In that case you got confirmation email from TED with subject like :
Your notice 0097de15-36cf-4750-96c9-f66ae4d6cafd-02 is submitted

Can you please confirm? thanks.

**Comment by haroonalam16** [comment]
Can you please also try to re-submitt the following notices:
d0c196ce-ab7a-4426-a62e-fe2d77b81ed0
417a58b4-813b-4df3-bb50-59119e68569e

**Comment by jlouvrier** [comment]
0097de15-36cf-4750-96c9-f66ae4d6cafd is submitted, message received from TED

**Comment by jlouvrier** [comment]
We will resubmit asap the following ones:
d0c196ce-ab7a-4426-a62e-fe2d77b81ed0
417a58b4-813b-4df3-bb50-59119e68569e

**Comment by jlouvrier** [comment]
V2 now submitted for both notices.

**Comment by haroonalam16** [comment]
Great, I will follow them.

**Comment by haroonalam16** [comment]
I can see following Notices are submitted successfully:
d0c196ce-ab7a-4426-a62e-fe2d77b81ed0-02 (N16)
417a58b4-813b-4df3-bb50-59119e68569e-02 (16 til TED)

**Comment by jlouvrier** [comment]
Same issue with ce7fedfd-3653-4742-a24b-04dc41774d76

Please advise

**Comment by haroonalam16** [comment]
Notice  ce7fedfd-3653-4742-a24b-04dc41774d76 (03.11.2023)is found in the system but unfortunately couldn't be able to submitted. 

**Can you please re-submit  ce7fedfd-3653-4742-a24b-04dc41774d76**

More, I found two more Notices in our system which i suspect couldn't be able to submitted:
2b4b9690-7e52-4d4b-b36e-4af1def47839 (03.11.2023)
5ba83ac0-12c5-4050-8194-c41ed2086692 (31.10.2023)

Can you please check that too in your system?

**Comment by jlouvrier** [comment]
@haroonalam16 what is the underlying problem here? Is it the notice itself or some logic on your end?

**Comment by haroonalam16** [comment]
It looks like problem is at our end for those mentioned Notices. 

We are continuously working to solve such issues and improve the system.

**Comment by jlouvrier** [comment]
All the 3 notices above are now resubmitted

**Comment by haroonalam16** [comment]
Great, I can already see that all 3 notices you re-submitted has status SUBMITTED in our system.

ce7fedfd-3653-4742-a24b-04dc41774d76-02
2b4b9690-7e52-4d4b-b36e-4af1def47839-02
5ba83ac0-12c5-4050-8194-c41ed2086692-02
