### ISSUE TITLE
Notice submitted 30.10.2023 and still in "MANUAL_CHECK"

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#39]
417b78fd-1a50-4501-ac6f-0fb29d9d13a4

What is the status of this notice? Should we resubmit?

**Comment by haroonalam16** [comment]
Unfortunately Notice 417b78fd-1a50-4501-ac6f-0fb29d9d13a4 which should be submitted to TED without problem but emerged as MANUAL_CHECK status. We are working on solution to avoid such scenarios in future.

But this time can you please re-submit the notice?
