### ISSUE TITLE
Another notice which ended up in Manual_Check

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#40]
0dda73e8-794e-4449-9ca2-c0a01357012c, no validation error

Should it be resubmitted?

**Comment by haroonalam16** [comment]
Yes, please re-submit the Notice 0dda73e8-794e-4449-9ca2-c0a01357012c

Can you also please re-submit  all the Notices which has status MANUAL_CHECK?

Sorry for inconvenience but we are working to improve the system to handle the problem causing the "MANUAL_CHECK" status.

**Comment by jlouvrier** [comment]
@haroonalam16 Please provide me with the full list of notices having this status on your end.
