### ISSUE TITLE
Will notices with subtype N16 validate without BT-67 Exclusion grounds?

### ISSUE THREAD

**Issue by Colan71** [anskaffelser/eforms-sdk-nor#41]
Hi,
I recall Rune telling us at a meeting yesterday that we can remove the mandatory flag for Exclusion grounds (BT-67(a)-Procedure) in national subtype N16. Can you please confirm that notices will not fail validation if we make Exclusion grounds optional in N16?

Best regards,
Åsa

**Comment by haroonalam16** [comment]
Hello,

As a general rule it's good idea to validate the Notice by calling the validate endpoint:
https://api.doffin.no/api/v2/notice/notices/validate 

If it is validated then you can use submit endpoint to submit the notice.

Or it is also possible to test such things within our Test environment before sending to Prod  environment.

Best regards,
Haroon

**Comment by kjorlaug** [comment]
The validation of the national forms (N-forms) is not as strict as for EU forms - so it will pass an N16 form that do not have BT-67 data. You are free to validate this by using the validator above or the one available on anskaffelser.dev.
