### ISSUE TITLE
National notice resubmitted and still not published

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#42]
Notice: d0c196ce-ab7a-4426-a62e-fe2d77b81ed0

We resubmitted this one earlier today and the status tonight is still "SUBMITTED". 

My expectation for national forms would be to see them being published immediately to DOFFIN. Has something changed?

**Comment by kjorlaug** [comment]
As it is now they get published at 9 the following day

tor. 9. nov. 2023, 21:39 skrev Julien Louvrier ***@***.***>:

**Comment by haroonalam16** [comment]
Notice: d0c196ce-ab7a-4426-a62e-fe2d77b81ed0 is published.
https://doffin.no/notices/2023-100709
