### ISSUE TITLE
Inconsistent Stop API

### ISSUE THREAD

**Issue by agnelgonsal** [anskaffelser/eforms-sdk-nor#43]
Hi Doffin team,

We notice that the Stop Publication API does not return consistent results.

To give you more details - When I was testing yesterday (09/11) evening between 20:15 and 20:35 hrs. UTC, I published 3 notices and stopped them and everything worked really well, following are the URL for the stop API call -

https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/78644c82-8174-47e4-b0c6-941d6cee1e7e-01/stop-publication-esentool?d=''
https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/8ddc336c-33ab-4e2a-9345-535769649aa9-01/stop-publication-esentool?d=''
https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/a18ed25f-85cf-497e-8be3-33cfcc5710d5-01/stop-publication-esentool?d=''

Today (10/11), when I test, I published a notice - 943bacdb-fdb0-4119-80c1-a43760718ac0-01 successfully.
But when I try to stop publication, I see an error - 404 NotFound
I am able to see the notice in the list in the response from the Search Notice API
The stop tests are done between 8:30 and 9:00 hrs. UTC today and it fails everytime, and I use the following URL -
https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/943bacdb-fdb0-4119-80c1-a43760718ac0-01/stop-publication-esentool?d=''

We have not changed anything from our side but see inconsistent results.

Thank you.

Kind Regards,
Agnel Gonsalves

**Comment by haroonalam16** [comment]
Hello Agnel Gonsalves,

I can see Notice 943bacdb-fdb0-4119-80c1-a43760718ac0-01 was submitted at 09:34, which was successfully submitted to TED at 10:10.
When you tried Notice was not submitted to TED system. If you will try to STOP the notice call will be successful.

Each time you submit the Notice to TED you get confirmation email directly from TED, so please always try to stop Notice once you received confirmation email from TED.

Best Regards,
Haroon
