### ISSUE TITLE
Notice status API returns status "SUMITTED"

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#44]
See API response for the following notice: 84cca2d4-0891-4e51-aed3-3ab0d816582f

{
    "totalSize": 1,
    "content": [
        {
            "id": "84cca2d4-0891-4e51-aed3-3ab0d816582f",
            "versionId": "01",
            "publicationId": null,
            "ngoj": null,
            "publicationDate": null,
            "procedureId": "1e833ad2-1d61-46ee-ad27-5232c03ead9f",
            "status": "SUMITTED",
            "updatedAt": null,
            "submittedAt": "2023-11-02T11:05:36.54061+01:00",
            "noticeType": "16",
            "legalBasis": "32014L0024",
            "languages": [
                "NOR",
                "ENG"
            ],
            "noticeAuthor": "publication@mercell.com"
        }
    ]
}

**Comment by haroonalam16** [comment]
Hello,
It was human mistake (Probably mine), sorry for that.
I think this notice was in MANUAL_CHECK status and when I tried to re-submit it happened. Thanks for your feedback, surely we need some better routines in such cases which eventually we will do.
 
84cca2d4-0891-4e51-aed3-3ab0d816582f is submitted to TED.
