### ISSUE TITLE
API returned Validation failed status, but validation report cannot be found

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#45]
"code": "notice.NOTICE_VALIDATION_REPORT_NOT_FOUND",
    "message": "Notice(84cca2d4-0891-4e51-aed3-3ab0d816582f-01) has no report"

Please investigate.

Thank you.

**Comment by haroonalam16** [comment]
Hello,
Yes, validation report was missing. I tried to make it available. Can you please try to access it?

Haroon

**Comment by jlouvrier** [comment]
Thanks, it is there now
