### ISSUE TITLE
Doffin validation API returns false whereas Validator website and TED validation API successfully validate the same file

### ISSUE THREAD

**Issue by aso-ivalua** [anskaffelser/eforms-sdk-nor#46]
Hello, 
Yesterday I noticed that all my test notices were failing using the doffin validation API, but they are successfully validated by the validation website (https://anskaffelser.dev/service/validator/) and by the TED api (after transformation using _nor-to-eforms.xslt_).
I even tried with a file that was previously validated by the API but it now just returns 'success: false'.

Please find the file in attachment.
Thank you
[pin_only.txt](https://github.com/anskaffelser/eforms-sdk-nor/files/13347476/pin_only.txt)

**Comment by erik-itland** [comment]
I will take a look at it.

**Comment by erik-itland** [comment]
It seems the file has been submitted to TED from our side. I write seems because what I have is an svrl-report which isn't supposed to be there unless we have sent the file, but I haven't traced it out yet.

If it is sent to TED you should have received a mail with a report to that email address. Could you paste the body of that email here if you have received it?

**Comment by aso-ivalua** [comment]
You are right, this notice ID was submitted previously and I am aware that
the submission API is supposed to fail. However, the validation API should
still give success because the format is correct. I also have other non
submitted examples of correct notices that pass the online validator but
not the validations api.

Here is the last email for this notice :

Your notice *6e2ad497-1da6-4dae-a63c-39ffcf19a8b9-01* has been published,
you can see it in your account with the status "Published".

Thank you

Le mar. 14 nov. 2023 à 12:07, erik-itland ***@***.***> a
écrit :

**Comment by aso-ivalua** [comment]
Here is an example of a file not yet submitted that passes the validation website but not the validation API.

Validator URL: https://anskaffelser.dev/service/validator/224dec42-d413-461f-bf87-2b7a07fec76e
File: 
[Dof_Notice20231114125730.txt](https://github.com/anskaffelser/eforms-sdk-nor/files/13349027/Dof_Notice20231114125730.txt)

**Comment by erik-itland** [comment]
Hi again!

We just discovered one interesting detail:

If we change the filename to "pin_only.xml" it validates fine.

We are already looking into the code to figure out why this happens, but until then, as a workaround, can you try submitting the files with the extension ".xml" ?

**Comment by erik-itland** [comment]
Do you by any chance use Windows notepad to adjust the files? I'm guessing here because of the .txt file extension and the fact that the file includes a BOM even if it is otherwise a UTF-8-file and that is something older versions of Notepad in Windows is known to do.

I am still looking into how we can accommodate your files. In my opinion, if the files validate in TED or the anskaffelser.dev validator they should validate in our code as well.

PS: I just realized one thing about the xml/txt thing: It wasn't related to the changing of the file extension but to the fact that we had opened the file in our IDE and saved a copy with the file extension .xml which meant that the BOM was removed.

**Comment by aso-ivalua** [comment]
Hello,

I renamed my original xml file to .txt only because github doesn’t allow
uploading an xml file. You can get the xml file from my last anskaffelser
link by clicking on download source.

Le mer. 15 nov. 2023 à 10:20, erik-itland ***@***.***> a
écrit :

**Comment by erik-itland** [comment]
Hi again!

I have now finished a PR to fix the issues you were seeing and it has also been appproved, merged and should now be live in the testing environment. 

Please let me know when you have had time to test it and feel free to send a few more files as well if the first file works.

**Comment by aso-ivalua** [comment]
It is working now indeed ! thank you very much

**Comment by erik-itland** [comment]
No problem and thanks for closing the issue! Have a nice day!

**Comment by kjorlaug** [comment]
Hi @aso-ivalua - I see that you are using version 1.6 of the SDK (we see that in the CustomizationId). Would you consider to start using 1.7 or 1.8 instead? TED will stop supporting 1.6 by the end of March next year. Supporting versions prior to 1.7 makes maintaining the national forms (N*) more complex for us, so if possible we would like to stop supporting it soon.

--

Rune

**Comment by aso-ivalua** [comment]
Hi @kjorlaug ,
It seems we are encountering the same issue again with notices in BOM format failing on 1.6. When using the same file in 1.7 the validation is successful. We are in the process of switching to either 1.7 or 1.8 right now, we are able to successfully validate basic notices where only the required information is filled. However, we do not use your sdk so all rules are manually implemented in our product. In order to fully switch to 1.7 in production we need to make sure that any new rules or other changes are covered. 
Is there any document that can help identify the changes from 1.6 to 1.7 (or 1.8).
Thank you

**Comment by erik-itland** [comment]
FWIW I'll just mention that in the dev environment I have already removed the 1.6 SDK this week so the reason why 1.6 doesn't work anymore is because there are nothing

**Comment by aso-ivalua** [comment]
Then we have to switch to 1.7 right away, we will implement any rules as we encounter them, but we won't be able to make sure that we cover all scenarios.
Again, if you have any summary of changes between 1.6 and 1.7, it will be of huge help.
