### ISSUE TITLE
Encoding issue in Public API

### ISSUE THREAD

**Issue by adamssonj** [anskaffelser/eforms-sdk-nor#47]
The public API is not handling encoding of Norwegian characters correctly. The notice in question looks very strange even on your own page: https://www.doffin.no/notices/2023-100777. Note that this problem is not limited to this notice.

* In what character encoding are you sending the notices through the public API?
* Why are you not including an XML tag with encoding in your eForms? e.g. <?xml version="1.0" encoding="UTF-8">

Highly appreciated to get some assistance on this issue

**Comment by kjorlaug** [comment]
Thank you for the heads up - this is due to a known issue on wrong interpertation of charset of incoming data (on byte level, not xml-parsing) that we are working to resolve. Everything is supposed to be UTF-8. @haroonalam16 will update you when this is fixed in production :)

--

Rune

**Comment by adamssonj** [comment]
Thank you for the quick response!

**Comment by sandrawiborg** [comment]
Hi @adamssonj  The charset problem is fixed, so I close this issue. Please let us know if you still experience any errors regarding this error.
