### ISSUE TITLE
Changed notices in Public search API

### ISSUE THREAD

**Issue by adamssonj** [anskaffelser/eforms-sdk-nor#48]
This notice: https://www.doffin.no/notices/2023-101091 has two versions, and both are available to download with the public download API.

My question is whether all version of the notice is available to find with the search API? If yes, does it require any specific query parameter? I could not find any information regarding this, and could not find the original notice version in the search API either.

Also, it would be much appreciated if you could provide all the available enums for e.g. `type`. 

Thank you

**Comment by 577854** [comment]
I don't work on the API but i noticed the same problem. I have figured out a solution for my program but I'm not sure if it is correct.  

The notice you are reffering to, seems to be a change notice of the original notice "https://www.doffin.no/notices/2023-101038".

When you do an API request (https://api.doffin.no/public/v2/download/2023-101091) for the change notice, you should see a <Changes> tag with a <ChangedNoticeIdentifier> tag that has a Guid value and an added "-01" to the Guid. 

This Guid (without the last 3 characters "-01") shows up in the API response for the original notice (https://api.doffin.no/public/v2/download/2023-101038). The tag <cbc:ID schemeName=\"notice-id\"> should have the same Guid value so you can track which notice was changed. 

For the notice you mentioned:
2023-101091(Change)
```xml
<efac:Changes>
  <efbc:ChangedNoticeIdentifier>2baf2ad2-87ec-488e-81ee-eb5996da25a3-01</efbc:ChangedNoticeIdentifier>
    <efac:Change>
      <efac:ChangedSection>
        <efbc:ChangedSectionIdentifier>PROCEDURE</efbc:ChangedSectionIdentifier>
      </efac:ChangedSection>
    </efac:Change>
```
2023-101038(Original)
```xml
<cbc:ID schemeName="notice-id">2baf2ad2-87ec-488e-81ee-eb5996da25a3</cbc:ID>
```
Here you can see that the identifying ID is 2baf2ad2-87ec-488e-81ee-eb5996da25a3


If anyone at Doffin can confirm that this is correct or wrong please correct me.

**Comment by 577854** [comment]
@adamssonj are you going to make changes to the notice-id Guid so that it is a DoffinID string in the future, and if so, when and how will that look in the xml responses?
