### ISSUE TITLE
SDK 1.7.2 rc2 leads to failed validation

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#49]
I am testing new Doffin SDK, version 1.7.2, rc2, https://github.com/anskaffelser/eforms-sdk-nor/releases/tag/v20231129-rc2

Notice subtype N16
Only mandatory fields are filled in. I would expect the following errors to not occur.

**Error**: Information under 'ND-LotReservedParticipation' is missing (element 'cac:TendererQualificationRequest' is mandatory under this path: */cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']cac:TenderingTerms)
Thrown by national-eforms-static.xslt. Expects at least one element to be added.
Candidates in national.json are:
* BT-76-Lot (optional)
* BT-761-Lot (optional)
* BT-771-Lot (optional)
* BT-772-Lot (optional)

**Error**: Information under 'ND-NonUBLTenderingTerms' is missing (element 'ext:UBLExtensionsext:UBLExtension/ext:ExtensionContent/efext:EformsExtension' is mandatory under this path: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']cac:TenderingTerms)
Thrown by national-eforms-static.xslt. Expects at least one element to be added.
Candidates in national.json are: 
* EU funding related fields (removed)
* selection criteria related fields (optional)
* strategic procurement related fields, CVD (removed)
* Subcontracting Tender Indication (removed)

There could be more wrong validation scenarios in the same subtype and different subtypes.

Could you confirm if this release candidate is well-tested and ready to be used?

**Comment by eduardsmirnov** [comment]
Notice subtype N4
Only mandatory fields are filled in.

**Error**: Information under 'ND-Part' is missing (element 'cac:ProcurementProjectLot[cbc:ID@schemeName='Part']' is mandatory under this path: *)
I did not investigate what fields could go there.

**Comment by eduardsmirnov** [comment]
Notice subtype N4
Field OPT-301-Part-ReviewOrg is made mandatory in national.json 
when it is added as required, national-eforms-static.xslt throws validation error "OPT-301-Lot-ReviewOrg is not allowed in notice type 'N4'"

**Comment by kjorlaug** [comment]
Is it your validator implementation that fails, or are you using one of ours?

**Comment by kjorlaug** [comment]
Thanks for input. Ee are investigating a bit further - we have run into similar problems running EFX transformations.

**Comment by kjorlaug** [comment]
We reintroduced BT-71-Part and BT-634-Lot in the latest build https://github.com/anskaffelser/eforms-sdk-nor/actions/runs/7022320460. Can you check if that resolved the two first issues?

**Comment by kjorlaug** [comment]
We're trying a new approach in RC3 to solve the issue
