### ISSUE TITLE
implimentering av eforms

### ISSUE THREAD

**Issue by Ballzer0** [anskaffelser/eforms-sdk-nor#5]
Hei, Jobber i Sykehusinnkjøp HF, og undersøker muligheten med og direkte integrere med nye eForms fra vår intærne løsning.

Ser dette er i "Pre Release" nå. er dette et prosjekt vi skal følge med på? eller skal vi bare ta utganspunkt i eForms-SDKen publisert av TED? https://github.com/OP-TED/eForms-SDK

**Comment by kjorlaug** [comment]
Hei

Du er på rett plass - det er her vi oversetter til norsk og tilgjengeliggjør norske skjema for under terskel. Dette prosjektet er i praksis en kompilator som "oversetter" TED sitt til norske forhold, så se gjerne til TED sitt repo for dokumentasjon av innhold mm. Ta kontakt med oss på doffin@dfo.no for mer informasjon.

Mvh

Rune
