### ISSUE TITLE
Doffin Notices API i dev er nede

### ISSUE THREAD

**Issue by kayjohnsen** [anskaffelser/eforms-sdk-nor#52]
Doffin Notices API i dev er nede (gir timeout feilmelding) og har vært det siden i går ettermiddag. Er det kun hos meg eller er det et problem? @haroonalam16

**Comment by kjorlaug** [comment]
Vi sjekker opp litt. Kan være i sammenheng med utrulling av ny SDK i test/dev som blei gjort i går.

**Comment by kjorlaug** [comment]
No skal det være oppe igjen.
