### ISSUE TITLE
Missing notices for April 2023?

### ISSUE THREAD

**Issue by AudunWA** [anskaffelser/eforms-sdk-nor#53]
When querying the search endpoint, I only get 17 results:
`https://api.doffin.no/public/v2/search?issueDateFrom=2023-04-01&issueDateTo=2023-04-30&page=1&numHitsPerPage=100`

That number seemed too low, so we checked Doffin Classic, which returns a lot more:
https://classic.doffin.no/Notice?pageNumber=1&pageSize=100&OrderingType=0&OrderingDirection=1&IsAdvancedSearch=false&IncludeExpired=false&PublishedFromDate=01.04.2023&PublishedToDate=30.04.2023

**Comment by kjorlaug** [comment]
Det skal være minst 155 der. Mistenker at det er søkeindeksen som ikkje er heilt i sync på historiske data. Skal sjekke opp litt.

**Comment by kjorlaug** [comment]
We have reimported historical data (was done a few weeks ago) - so issue should be resolved now :)
