### ISSUE TITLE
Validering av Procedure planned period

### ISSUE THREAD

**Issue by kayjohnsen** [anskaffelser/eforms-sdk-nor#54]
Jeg får `"success": false` når jeg bruker APIet (validate notice) deres til å validere PlannedPeriod og sluttdato er ukjent

`<cac:PlannedPeriod>
    <cbc:StartDate>2024-01-01+01:00</cbc:StartDate>
    <cbc:DescriptionCode listName="timeperiod">UNKNOWN</cbc:DescriptionCode>
</cac:PlannedPeriod>`

Jeg tolker den offisielle dokumentasjonen som at dette skal være tillatt:
![image](https://github.com/anskaffelser/eforms-sdk-nor/assets/26326670/0d327e5c-a7c8-4837-b333-48ae367c0520)

Valideringen deres gir godkjent her:
![image](https://github.com/anskaffelser/eforms-sdk-nor/assets/26326670/632289d7-99cb-4fde-8aa9-c4d376595987)

Hva er riktig? Hvordan skal XML se ut hvis startdato er kjent, mens sluttdato er ukjent?

**Comment by kjorlaug** [comment]
Er det eit nasjonalt skjema (N*) du prøver å validere?

**Comment by kayjohnsen** [comment]
> Er det eit nasjonalt skjema (N*) du prøver å validere?

Ja

**Comment by kjorlaug** [comment]
Vi har skrudd til validering av nasjonale skjema i test-miljøet til Doffin (RC3-release som er der no). Førre validering (som enno er live på anskaffelser.dev var for slapp).

Det er litt diskusjon rundt dette på TED sin github, og det ser for meg ut til at dei har hatt litt strenge reglar på dette i 1.7-1.9 SDKane. Det er blanding av dato og description som blir feil i ditt eksempel. Du kan anten angi datoperiode med ein slutt langt fram i tid:
`<cac:PlannedPeriod> 
<cbc:StartDate>2024-01-01+01:00</cbc:StartDate> 
<cbc:EndDate>2099-12-31Z</cbc:EndDate> 
</cac:PlannedPeriod>`

eller berre kode:
`<cac:PlannedPeriod> 
<cbc:DescriptionCode listName="timeperiod">UNKNOWN</cbc:DescriptionCode> 
</cac:PlannedPeriod>`
