### ISSUE TITLE
Notice seems stuck in status submitted 

### ISSUE THREAD

**Issue by MaxKholoshnyi** [anskaffelser/eforms-sdk-nor#55]
Good morning 
We send a notice on firday mornign 2023-12-15T09:53:55.999577+01:00
Notice id : 26d3c9e2-9cef-49c0-8998-b029a5c4ad51
But it still remains in status submitted.
Can you please have  alook to it?

**Comment by kjorlaug** [comment]
Good morning!

The notice is recieved and is now published by TED as we speak, so status was just changed to Published in the system. With the current publishing regime in the new Doffin we wait for TED publication before Doffin publishes, so it can (in theory) take up to 5 business-days before status is changed.

--

Rune
