### ISSUE TITLE
Missing notice

### ISSUE THREAD

**Issue by MaxKholoshnyi** [anskaffelser/eforms-sdk-nor#57]
Good mornign 
We got a noctice with ID: 38619658-bbdf-43e7-82f0-52d4ab635a22
Sending it DOFFIN did not indicate success. As well error details were not specified in response. 
When I'm trying to get a status of the notice in DOFFIN i'm getting empty response. 
Do you guys, maybe, have some logs or any indication if you recieved the notice ?

**Comment by haroonalam16** [comment]
Hello,

Notice with ID 38619658-bbdf-43e7-82f0-52d4ab635a22 is not in our system. Can you please try to validate your notice:
https://api.doffin.no/api/v2/notice/notices/validate
