### ISSUE TITLE
Release 1.7 RC3 contains keyword "contratings", what is it?

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#58]
Release 1.7 RC3 contains keyword "contratings instead of "constraints". It is repeated many times. 
Is it a new keyword? Is it documented?

![image](https://github.com/anskaffelser/eforms-sdk-nor/assets/59865467/b794f3c6-afa2-49ec-9b9c-c9f552dc3438)

**Comment by kjorlaug** [comment]
It's a spelling error - fixed with latest commit. If you want to continue to test you can use the newly created artifacts on that you find on the build from the that commit. We will make it RC4 soon.
