### ISSUE TITLE
Notice published to TED but no PublicationId returned 

### ISSUE THREAD

**Issue by MaxKholoshnyi** [anskaffelser/eforms-sdk-nor#59]
Good morning. 
We have to notices (one as update to other). Both has status published in DOFFIN and both cna be found in TED but one of them does not have PublicaitonId whan we checking status of it.  Is there any specific reason for it?

            "id": "b4c3eabc-eabd-4808-ba52-b212b2beede4",
            "versionId": "01",
           "publicationId": "775184-2023",
            "ngoj": "2023-102844",
            "publicationDate": "2023-12-21",
            "status": "PUBLISHED",

          "id": "0735e100-11ce-478b-b18e-d416c8068576",
            "versionId": "01",
            "publicationId": null,
            "ngoj": "2023-103079",
            "publicationDate": "2023-12-22",
            "status": "PUBLISHED",

**Comment by haroonalam16** [comment]
Hello,
0735e100-11ce-478b-b18e-d416c8068576 is the Changing Notice and Doffin published it before the Notice is published in TED. Once Notice is PUBLISHED in Doffin we do not poll to check if it is published in TED and hence fetch TED publicationId.
