### ISSUE TITLE
Norwegian translations

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#6]
Just got a new version of Norwegian SDK for 1.6
Could you help to find Norwegian translations from there? In all translation files ending with nn, nb, nn-complete and nb-complete I can see only English texts. Am I looking at wrong place?

**Comment by kjorlaug** [comment]
You are looking at the right place. We have used the default (english) where there is translation missing.

The priority now is to get the infrastructure for distribution up and running, with the ability to support both EU and national forms (hence Norwegian), not providing translations to Norwegian of everything. That is a parallell ongoing process.

Hope that cleared things up a bit.
