### ISSUE TITLE
How to triggrer 1.7.2 validation

### ISSUE THREAD

**Issue by MaxKholoshnyi** [anskaffelser/eforms-sdk-nor#60]
Good morning 
We implemented  1.7 rc4 SDK but  when we are trying to validate the notice it's failing validaiton in DOFFIN

eforms-sdk-1.7-nor-20231213-rc4 -  does not have "rule|text|BR-BT-00262-0211" so it passes validaiton on our side

When I trying to Validate it validates against 1.7.1 
https://anskaffelser.dev/service/validator/f0b17f48-3b0e-4284-94d1-b32b16e6e8ac

**Comment by haroonalam16** [comment]
Hi,
Can you try to validate Notice with:
https://betaapi.doffin.no/api/v2/notice/notices/validate?debug=true

**Comment by MaxKholoshnyi** [comment]
I do not have a subscription key for BetaApi  so getting 401

**Comment by haroonalam16** [comment]
Please check the following page for more info and access to testing and development:
https://github.com/anskaffelser/eforms-sdk-nor/blob/main/README.md
