### ISSUE TITLE
Issue with publication to TED?

### ISSUE THREAD

**Issue by Colan71** [anskaffelser/eforms-sdk-nor#61]
Hi,
Is there some issue with publishing change notices to TED? We get Doffin status PublishedNational for some of the changes instead of TED status Published. Can you please check this out. 

Some examples. 
Form id:65855ef8c36b880de6ed8893, Directive: 32014L0024, Notice type: cn-standard, Type: competition, Subtype: 16, Status: PublishedNational

Form id:65967f788802f63d1b350d3a, Directive: 32014L0024, Notice type: cn-standard, Type: competition, Subtype: 16, Status: PublishedNational

Kind regards,
Åsa

**Comment by Colan71** [comment]
Seems like the notices are published to TED, but then my question is why we do not get the TED status Published back?


BR,
Åsa

**Comment by haroonalam16** [comment]
Hello,
Can you please provide me the eform-id for the notice in question in valid format so i can check it.

In general, If Notice is ChangesNotice, Doffin published it right away before the Notice is published in TED (Doffin do not send any confirmation email). Once Notice is PUBLISHED in Doffin we do not poll to check if it is published in TED. 
Later when Notice also published in TED, Ted send confirmation e-mail with status PUBLISHED.

Regards,
Haroon

**Comment by Colan71** [comment]
Change notice ID: 9137eea3-13ba-4381-8fe5-24fca8479125-01
TED ID: 00787749-2023


But is this some recent change in the handling of change notices on your side? That you publish a change straight away on Doffin before it is published on TED? For other TED change notices for the same tender we have received status "Published". 
And shouldn't you poll to make sure that the notice is successfully published on TED and get the correct status and ID? 

Examples of previous statuses of several changes within the same tender:
Original notice id: 833a5a7b-effb-4d9c-ae39-5e2a5fd7a483
And the change notice ID's:
833a5a7b-effb-4d9c-ae39-5e2a5fd7a483-01
1b1d89c6-7732-4da8-8993-090372b12bba-01
1b1d89c6-7732-4da8-8993-090372b12bba-01
caf7cbb2-3b93-4793-94ca-48dafb544218-01



Form id:654221221c5e0bc479dee23c, Directive: 32014L0024, Notice type: cn-standard, Type: competition, Subtype: 16, Status: Published
 — Form id:65796979ac40ad16a3bed22d, Directive: 32014L0024, Notice type: cn-standard, Type: competition, Subtype: 16, Status: Published
  — Form id:657fffcd9f6559c6ee4d7686, Directive: 32014L0024, Notice type: cn-standard, Type: competition, Subtype: 16, Status: Published
   — Form id:6582facde80ee72b0048ce57, Directive: 32014L0024, Notice type: cn-standard, Type: competition, Subtype: 16, Status: Published
    — Form id:65967f788802f63d1b350d3a, Directive: 32014L0024, Notice type: cn-standard, Type: competition, Subtype: 16, Status: PublishedNational

**Comment by haroonalam16** [comment]
Yes, we implemented it recently that Change Notice Publish straight away on Doffin before it is Published on TED. When Doffin Publish the Notice it assign Doffin id, for Change notice ID: 9137eea3-13ba-4381-8fe5-24fca8479125-01 it is 2023-103076.
yes, in that case tedid is missing, but we already have internal case to implement functionality to fetch tedid.

**Comment by Colan71** [comment]
Does this mean that when the functionality to fetch TED id is in place, we will receive both status Published and the ID? The fact the we now only get the Doffin status is causing issues since we need to have the confirmation that TED published the notice successfully in order for our customers to be able to make changes etc.
 
@kjorlaug

**Comment by Colan71** [comment]
When did you introduce this publishing procedure for change notices? Can you please give me the date for when it started?

What would be the best solution for us is to get the TED status PUBLISHED, the time stamp for it and the TED ID so we have the exact status changes and execution date/time for each publication event.

**Comment by haroonalam16** [comment]
We have implemented the logic for publishing for changes notices on 18 December 2023. 

We already working a solution to fetch/sync tedid and execution date/time for changes Notices from TED. Once Solution be in place it will not only sync changes Notices with TED for new changes notices but at the same will also update the missing tedid etc for all changes Notices from 18 December. I am hoping solution will be available next week.

**Comment by CharlotteKolle** [comment]
@Colan71 - the solution to fetch/sync TEDid as Haroon described above is now in production.
