### ISSUE TITLE
Missing notice for download (2024-100149) 

### ISSUE THREAD

**Issue by 577854** [anskaffelser/eforms-sdk-nor#62]
When i get notices from 04.01.2024 with https://api.doffin.no/public/v2/search?issueDateFrom=2024-01-04&issueDateTo=2024-01-04 i get one notice with id 2024-100149. It shows up with the link https://www.doffin.no/notices/2024-100149 but when i try and get it with the download API (https://api.doffin.no/public/v2/download/2024-100149) i get 404 not found.

**Comment by haroonalam16** [comment]
Hello,
Can you please try it now? It should be available now because service was updating the download list (around 11:00) when you tried to download the notice.
