### ISSUE TITLE
502 Error accessing Validator

### ISSUE THREAD

**Issue by MaxKholoshnyi** [anskaffelser/eforms-sdk-nor#63]
hi guys, 
i'm getting error when trying to open URL: https://anskaffelser.dev/service/validator/
Next that as well validaiton though postman started giving me 500 from yesterday 
https://api.doffin.no/api/v2/notice/notices/validate

Is it outage ot you just migrating URLs and we shall start using different one?

**Comment by kjorlaug** [comment]
These are two distinct/different services - the ans.dev validator is up and running again. Thanks for the heads up :)
