### ISSUE TITLE
Notice publication is failing, API response is not very helpful

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#64]
Hi,
We are trying to publish the notice below and getting the validation error "success": false
As it is not very informative, I would appreciate some help figuring out what is wrong.
Thank you,
Julien (Mercell)

`<?xml version="1.0" encoding="utf-8"?>
<ContractAwardNotice xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:efac="http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1" xmlns:efext="http://data.europa.eu/p27/eforms-ubl-extensions/1" xmlns:efbc="http://data.europa.eu/p27/eforms-ubl-extension-basic-components/1" xmlns="urn:oasis:names:specification:ubl:schema:xsd:ContractAwardNotice-2">
  <ext:UBLExtensions>
    <ext:UBLExtension>
      <ext:ExtensionContent>
        <efext:EformsExtension>
          <efbc:TransmissionDate>2024-01-23+00:00</efbc:TransmissionDate>
          <efbc:TransmissionTime>15:10:21+00:00</efbc:TransmissionTime>
          <efac:NoticeResult>
            <efac:LotResult>
              <cbc:ID schemeName="result">RES-0001</cbc:ID>
              <cbc:TenderResultCode listName="winner-selection-status">selec-w</cbc:TenderResultCode>
              <efac:LotTender>
                <cbc:ID schemeName="tender">TEN-0001</cbc:ID>
              </efac:LotTender>
              <efac:LotTender>
                <cbc:ID schemeName="tender">TEN-0002</cbc:ID>
              </efac:LotTender>
              <efac:SettledContract>
                <cbc:ID schemeName="contract">CON-0001</cbc:ID>
              </efac:SettledContract>
              <efac:TenderLot>
                <cbc:ID schemeName="Lot">LOT-0000</cbc:ID>
              </efac:TenderLot>
            </efac:LotResult>
            <efac:LotTender>
              <cbc:ID schemeName="tender">TEN-0001</cbc:ID>
              <efac:TenderingParty>
                <cbc:ID schemeName="tendering-party">TPA-0002</cbc:ID>
              </efac:TenderingParty>
              <efac:TenderLot>
                <cbc:ID schemeName="Lot">LOT-0000</cbc:ID>
              </efac:TenderLot>
              <efac:TenderReference>
                <cbc:ID>23/15815</cbc:ID>
              </efac:TenderReference>
            </efac:LotTender>
            <efac:LotTender>
              <cbc:ID schemeName="tender">TEN-0002</cbc:ID>
              <efac:TenderingParty>
                <cbc:ID schemeName="tendering-party">TPA-0001</cbc:ID>
              </efac:TenderingParty>
              <efac:TenderLot>
                <cbc:ID schemeName="Lot">LOT-0000</cbc:ID>
              </efac:TenderLot>
              <efac:TenderReference>
                <cbc:ID>23/15815</cbc:ID>
              </efac:TenderReference>
            </efac:LotTender>
            <efac:SettledContract>
              <cbc:ID schemeName="contract">CON-0001</cbc:ID>
              <cbc:AwardDate>2024-01-18+01:00</cbc:AwardDate>
              <cbc:IssueDate>2024-01-19+01:00</cbc:IssueDate>
              <efbc:ContractFrameworkIndicator>false</efbc:ContractFrameworkIndicator>
              <cac:SignatoryParty>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
                </cac:PartyIdentification>
              </cac:SignatoryParty>
              <efac:ContractReference>
                <cbc:ID>23/270918</cbc:ID>
              </efac:ContractReference>
              <efac:LotTender>
                <cbc:ID schemeName="tender">TEN-0001</cbc:ID>
              </efac:LotTender>
            </efac:SettledContract>
            <efac:TenderingParty>
              <cbc:ID schemeName="tendering-party">TPA-0001</cbc:ID>
              <efac:Tenderer>
                <cbc:ID schemeName="organization">ORG-0003</cbc:ID>
              </efac:Tenderer>
            </efac:TenderingParty>
            <efac:TenderingParty>
              <cbc:ID schemeName="tendering-party">TPA-0002</cbc:ID>
              <efac:Tenderer>
                <cbc:ID schemeName="organization">ORG-0002</cbc:ID>
              </efac:Tenderer>
            </efac:TenderingParty>
          </efac:NoticeResult>
          <efac:NoticeSubType>
            <cbc:SubTypeCode listName="notice-subtype">N29</cbc:SubTypeCode>
          </efac:NoticeSubType>
          <efac:Organizations>
            <efac:Organization>
              <efac:Company>
                <cbc:WebsiteURI>http://www.politiet.no</cbc:WebsiteURI>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="NOR">Politiets fellestjenester</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:StreetName>Fridtjof Nansens vei 14</cbc:StreetName>
                  <cbc:CityName>OSLO</cbc:CityName>
                  <cbc:PostalZone>0369</cbc:PostalZone>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">NOR</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">974761157</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Name>Marianne Haahjem</cbc:Name>
                  <cbc:Telephone>+47 97541819</cbc:Telephone>
                  <cbc:ElectronicMail>marianne.haahjem@politiet.no</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
            <efac:Organization>
              <efac:Company>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0002</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="NOR">AFRY Norway AS</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:StreetName>Lilleakerveien 8</cbc:StreetName>
                  <cbc:CityName>Oslo</cbc:CityName>
                  <cbc:PostalZone>0283</cbc:PostalZone>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">NOR</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">915 229 719</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Telephone>+47 24101010</cbc:Telephone>
                  <cbc:ElectronicMail>anne.ranvig@afry.com</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
            <efac:Organization>
              <efac:Company>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0003</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="NOR">Habberstad AS</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:StreetName>Karenslyst alle 2</cbc:StreetName>
                  <cbc:CityName>Oslo</cbc:CityName>
                  <cbc:PostalZone>0278</cbc:PostalZone>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">NOR</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">974532700</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Telephone>+47 95752608</cbc:Telephone>
                  <cbc:ElectronicMail>helle.bjorge@habberstad.no</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
            <efac:Organization>
              <efac:Company>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0004</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="NOR">Oslo tingrett</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:StreetName>Postboks 2106 Vika</cbc:StreetName>
                  <cbc:CityName>OSLO</cbc:CityName>
                  <cbc:PostalZone>0125</cbc:PostalZone>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">NOR</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">926725939</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Telephone>+47 22035200</cbc:Telephone>
                  <cbc:ElectronicMail>oslo.tingrett@domstol.no</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
          </efac:Organizations>
        </efext:EformsExtension>
      </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>
  <cbc:UBLVersionID>2.3</cbc:UBLVersionID>
  <cbc:CustomizationID>eforms-sdk-1.7#extended#urn:fdc:anskaffelser.no:2023:eforms:national</cbc:CustomizationID>
  <cbc:ID schemeName="notice-id">6e1a6b54-b221-4ad4-8cb0-0d86879386fa</cbc:ID>
  <cbc:ContractFolderID>3eaca80e-6a2d-4f41-81ac-44414a4a401e</cbc:ContractFolderID>
  <cbc:IssueDate>2024-01-23+00:00</cbc:IssueDate>
  <cbc:IssueTime>15:09:35+00:00</cbc:IssueTime>
  <cbc:VersionID>01</cbc:VersionID>
  <cbc:RegulatoryDomain>other</cbc:RegulatoryDomain>
  <cbc:NoticeTypeCode listName="result">can-standard</cbc:NoticeTypeCode>
  <cbc:NoticeLanguageCode>NOR</cbc:NoticeLanguageCode>
  <cac:ContractingParty>
    <cbc:BuyerProfileURI>https://eu.eu-supply.com/ctm/company/companyinformation/index/289530</cbc:BuyerProfileURI>
    <cac:ContractingPartyType>
      <cbc:PartyTypeCode listName="buyer-legal-type">cga</cbc:PartyTypeCode>
    </cac:ContractingPartyType>
    <cac:ContractingActivity>
      <cbc:ActivityTypeCode listName="authority-activity">pub-os</cbc:ActivityTypeCode>
    </cac:ContractingActivity>
    <cac:Party>
      <cac:PartyIdentification>
        <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
      </cac:PartyIdentification>
    </cac:Party>
  </cac:ContractingParty>
  <cac:TenderingTerms>
    <cac:ProcurementLegislationDocumentReference>
      <cbc:ID>forskrift om offentlige anskaffelser</cbc:ID>
    </cac:ProcurementLegislationDocumentReference>
  </cac:TenderingTerms>
  <cac:TenderingProcess>
    <cbc:ProcedureCode listName="procurement-procedure-type">oth-single</cbc:ProcedureCode>
    <cbc:TerminatedIndicator>true</cbc:TerminatedIndicator>
  </cac:TenderingProcess>
  <cac:ProcurementProject>
    <cbc:ID schemeName="InternalID">23/270918</cbc:ID>
    <cbc:Name languageID="NOR">Innkjøpsfaglig bistand IKT anskaffelser anskaffelser</cbc:Name>
    <cbc:Description languageID="NOR">PFT, heretter også kalt oppdragsgiver, ønsker 1 konsulent til seksjon IKT anskaffelser for operativ bistand til gjennomføring av offentlige anskaffelser.  I den utstrekning oppdragsgiver ønsker det, skal Konsulenten også delta i andre aktiviteter som inngår i seksjonens arbeidsoppgaver.  IKT anskaffelser holder til på Majorstua i Oslo og består i dag av 10 personer som jobber dedikert med IKT anskaffelser i tett samarbeid med Politiets IT enhet (PIT). Vi har etablert gode prosesser som gjør at vi kan fokusere på hvordan anskaffelser kan bidra til å løse politiets kjerneoppgaver og samfunnsoppdrag. Konsulenten vil være ansvarlig for gjennomføring av anskaffelser i samarbeid med et spennende fagmiljø i utvikling og bidra til å forme fremtidens politi. </cbc:Description>
    <cbc:ProcurementTypeCode listName="contract-nature">services</cbc:ProcurementTypeCode>
    <cac:RequestedTenderTotal>
      <cbc:EstimatedOverallContractAmount currencyID="NOK">0</cbc:EstimatedOverallContractAmount>
    </cac:RequestedTenderTotal>
    <cac:MainCommodityClassification>
      <cbc:ItemClassificationCode listName="cpv">79418000</cbc:ItemClassificationCode>
    </cac:MainCommodityClassification>
  </cac:ProcurementProject>
  <cac:ProcurementProjectLot>
    <cbc:ID schemeName="Lot">LOT-0000</cbc:ID>
    <cac:TenderingTerms>
      <cbc:FundingProgramCode listName="eu-funded">no-eu-funds</cbc:FundingProgramCode>
      <cac:AppealTerms>
        <cac:AppealReceiverParty>
          <cac:PartyIdentification>
            <cbc:ID schemeName="organization">ORG-0004</cbc:ID>
          </cac:PartyIdentification>
        </cac:AppealReceiverParty>
      </cac:AppealTerms>
    </cac:TenderingTerms>
    <cac:TenderingProcess>
      <cbc:GovernmentAgreementConstraintIndicator>true</cbc:GovernmentAgreementConstraintIndicator>
      <cac:AuctionTerms>
        <cbc:AuctionConstraintIndicator>false</cbc:AuctionConstraintIndicator>
      </cac:AuctionTerms>
      <cac:ContractingSystem>
        <cbc:ContractingSystemTypeCode listName="dps-usage">dps-list</cbc:ContractingSystemTypeCode>
      </cac:ContractingSystem>
      <cac:ContractingSystem>
        <cbc:ContractingSystemTypeCode listName="framework-agreement">none</cbc:ContractingSystemTypeCode>
      </cac:ContractingSystem>
    </cac:TenderingProcess>
    <cac:ProcurementProject>
      <cbc:ID schemeName="InternalID">2</cbc:ID>
      <cbc:Name languageID="NOR">Innkjøpsfaglig bistand IKT anskaffelser anskaffelser</cbc:Name>
      <cbc:Description languageID="NOR">Anskaffelse av bistand til IT anskaffelser</cbc:Description>
      <cbc:ProcurementTypeCode listName="contract-nature">services</cbc:ProcurementTypeCode>
      <cac:RequestedTenderTotal>
        <cbc:EstimatedOverallContractAmount currencyID="NOK">0</cbc:EstimatedOverallContractAmount>
      </cac:RequestedTenderTotal>
      <cac:MainCommodityClassification>
        <cbc:ItemClassificationCode listName="cpv">79418000</cbc:ItemClassificationCode>
      </cac:MainCommodityClassification>
    </cac:ProcurementProject>
  </cac:ProcurementProjectLot>
  <cac:TenderResult>
    <cbc:AwardDate>2000-01-01Z</cbc:AwardDate>
  </cac:TenderResult>
</ContractAwardNotice>`

**Comment by kjorlaug** [comment]
If you include the parameter ?debug=true in the validation service you get this result:
```
{
    "success": false,
    "vefaValidation": {
        "title": "eForms 1.7 NOR (national)",
        "flag": "error",
        "section": [
            {
                "title": "XSD validation",
                "flag": "ok",
                "assertions": []
            },
            {
                "title": "eForms schematron rules",
                "flag": "error",
                "assertions": [
                    {
                        "identifier": "ND-AwardingTerms-29",
                        "text": "Information under 'ND-AwardingTerms' is missing (element 'cac:AwardingTerms' is mandatory under this path: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms)",
                        "locationInDocument": "/can:ContractAwardNotice[1]/cac:ProcurementProjectLot[1]/cac:TenderingTerms[1]",
                        "test": "count(cac:AwardingTerms) > 0",
                        "flag": "ERROR"
                    }
                ]
            },
            {
                "title": "Norwegian tailoring (national) for eForms 1.7.2",
                "flag": "ok",
                "assertions": []
            }
        ],
        "validFlags": [
            "ok",
            "warning"
        ]
    }
}

```
I suspect this is related to using 1.7.2 rules...

--

Rune
