### ISSUE TITLE
National contract notice validation fails

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#65]
Please see : https://anskaffelser.dev/service/validator/0e65acca-1459-4534-97df-2086dc84f224

Any idea why this notice is failing? I didn't expect ESPD Selection criteria to be mandatory on a national form.

**Comment by jlouvrier** [comment]
@kjorlaug Is someone looking into it?

**Comment by jlouvrier** [comment]
Any update?

**Comment by kjorlaug** [comment]
We need to look a bit deeper into this as this goes to SelectionCriteria in general, not ESPD. If you want to push this notice through now, try to add an selection criteria for tax certificate (skatteattest) as per the Norwegian regulation. That should make it validate.

--

Rune

**Comment by MaxKholoshnyi** [comment]
More exmaples 
https://anskaffelser.dev/service/validator/a1d54943-6d8e-4e9e-9d1c-68a4b3131133

**Comment by jlouvrier** [comment]
@kjorlaug @CharlotteKolle I would like to get clarity on your expectations regarding the validation of selection criteria (BT-747, 748, 749, 750) for N16 notices.

Selection criteria in eForms correspond to the categories defined in the ESPD. In our current implementation of N16 we do not require buyers to provide any selection criteria:

<img width="1691" alt="Screenshot 2024-02-08 at 9 28 14" src="https://github.com/anskaffelser/eforms-sdk-nor/assets/64864592/3534f90f-8ca0-4180-8f03-8b982855608a">

We can change the configuration and mark all of them, some of them, one of them as required.

**Comment by jlouvrier** [comment]
@kjorlaug @CharlotteKolle 

We did some further investigations today and found out that our notices are failing not due to Selection criteria, but due to **BT-71 Reserved participation - Lot**. 

Currently, DOFFIN API won't accept an N16 without a value for BT-71. This contradicts the spreadsheet 2023-11-02 Nasjonal tabell shared by Rune last week. I would like to have a meeting as soon as possible.

Example: https://anskaffelser.dev/service/validator/3bc9d8e8-760d-4606-bdb0-f6e60c56e12c
