### ISSUE TITLE
HTML response Resource not found from betaapi.doffin.no

### ISSUE THREAD

**Issue by ewlidd** [anskaffelser/eforms-sdk-nor#68]
I'm having issues using the dev API. Testing with queries that were working before now receive the following HTML response instead of the usual JSON:
`<html><body><h1>Resource not found</h1></body></html>`

e.g:
curl "https://betaapi.doffin.no/public/v2/search" -H "Cache-Control: no-cache" -H "Ocp-Apim-Subscription-Key: x"

**Comment by smgit-mercell** [comment]
We are also facing this exactly same issue.

**Comment by kjorlaug** [comment]
We will look into this after the weekend - thanks for giving a heads up!

**Comment by kjorlaug** [comment]
This was just due to a hickup in during update of the test-environment - sorry for the trouble (and the delay in answering)
