### ISSUE TITLE
Gjøre BT-501 (efac:Company​/cac:PartyLegalEntity​/cbc:CompanyID) obligatorisk?

### ISSUE THREAD

**Issue by AudunWA** [anskaffelser/eforms-sdk-nor#72]
Ut i fra det jeg kan se, har alle eForms i Doffin en kjøper spesifisert – men det er en del som kun inneholder navnet, og ikke org.nr. e.l. Vi bruker denne informasjonen aktivt, og må per nå bruke heuristikker for å mappe de tilfellene der feltet mangler eller ikke er et gyldig org.nr. 

Er det mulig å gjøre dette feltet obligatorisk for innsendinger til Doffin? Utover det hadde det også vært nyttig å validere verdien, f.eks. en regex for org.nr. og lignende, men forstår at det kan være for begrensende.

**Comment by AudunWA** [comment]
Hei igjen, @kjorlaug. Dette er fortsatt et utbredt problem, mange kunngjøringer som har manglende eller åpenbar feil verdi i BT-501.
1. Kan dere lage egendefinert validering i tillegg til det innebygde i eForms SDK-et? Enten før eller etter SDK-et gjør sitt i prosesseringen hos dere.
2. Har du noen lenke til hvor, eller mer informason om diskusjonen rundt innstramming i BT-501? Om det er mulig kan vi i Cobrief være interessert i å påvirke der også.

**Comment by bjornjorgensen** [comment]
@AudunWA Hei, anbefaler deg å kontakte OP TED.. har fått det gjort igjennom OCDS når de stod fast eks. https://github.com/OP-TED/eForms-SDK/discussions/1064
