### ISSUE TITLE
Fomr 29 passing validation but failing later in  a porcess 

### ISSUE THREAD

**Issue by MaxKholoshnyi** [anskaffelser/eforms-sdk-nor#74]
Good mornign we have a notice that passes validaion and DOFFIN accepts it, but later it's failing https://anskaffelser.dev/service/validator/440029f4-7e65-4790-8744-ec47300f7e6c

Noitce: 265845c7-5776-4f10-adde-7895a99d8848 Version 01 and 02

**Comment by kjorlaug** [comment]
Did you get this notice through in the end, or should I still investigate? At glance the notice seems ok, so to it would be great to get the TED error message if you want me to check more.

--

Rune

**Comment by MaxKholoshnyi** [comment]
@kjorlaug No this one we don't get all data seem to be in XML so it's somtheing for you to have a look.

**Comment by kjorlaug** [comment]
The "quality-nor-env-none" code on award criteria was not really intended used with weight as done here, but rather an indicator with weight 0, so it's removed before submitting to TED causing this error. But we see that this might be misunderstood :) 

The quick fix on this is just to use the standard "quality" code on the existing award criteria, or set the weight to 0 and add a new "quality" award criteria.

**Comment by kjorlaug** [comment]
The correct use of the code as informed in the 30% environment quide is weight 0 and description used to explain why :)
