### ISSUE TITLE
[dev] inconsistent results between webui and api

### ISSUE THREAD

**Issue by ewlidd** [anskaffelser/eforms-sdk-nor#76]
To best show this issue, return all results from issue date 2024-05-06 to issue date 2024-05-07:

**WEBUI**
https://beta.doffin.no/search?page=1&fromDate=2024-05-06&toDate=2024-05-07
134 results

**API**
`curl -v "https://betaapi.doffin.no/public/v2/search?issueDateFrom=2024-05-06&issueDateTo=2024-05-07" -H "Cache-Control: no-cache" -H "Ocp-Apim-Subscription-Key: xxxx"`
{"numHitsTotal":0,"numHitsAccessible":0,"hits":[]}

**Comment by haroonalam16** [comment]
Hello,
Sorry for in inconvenience, Please use the following URL to view the DEV Tenders?

https://dof-webclient-dev-app.azurewebsites.net/
https://dof-webclient-dev-app.azurewebsites.net/search?page=1&fromDate=2024-05-06&toDate=2024-05-07

Regards,
Haroon
