### ISSUE TITLE
[dev] cannot view tenders in webui

### ISSUE THREAD

**Issue by ewlidd** [anskaffelser/eforms-sdk-nor#77]
We cannot view tenders when clicking on them on the webui after searching. All return "kunngjøring ikke funnet"

example: click on any tender from the following link:
https://beta.doffin.no/search?page=1&fromDate=2024-05-06&toDate=2024-05-07
the first result in this search, for example: https://beta.doffin.no/notices/2024-106703

**Comment by haroonalam16** [comment]
Hello, 
For dev Tenders please use the following link:
https://dof-webclient-dev-app.azurewebsites.net

and for PROD us doffin.no
