### ISSUE TITLE
Submission error - how to know what happened?

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#8]
Just tried to submit a notice.
Got a response, see below. How do you expect users to understand what happened with a notice and why it cannot be submitted?
`{
    "success": false
}`

**Network dump from postman is** 
`POST https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/submit
400
1 m 17.64 s
POST /api/v2/notice/notices/submit HTTP/1.1
Ocp-Apim-Subscription-Key: XXXXXXXXXXXXXXXXXXXXXXXXXX
Cache-Control: no-cache
User-Agent: PostmanRuntime/7.32.2
Accept: */*
Postman-Token: a555067f-c084-40d7-81fc-ad97fcbcffb5
Host: dof-notices-dev-api.azure-api.net
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=--------------------------184126686857005263182509
Content-Length: 7777
 
----------------------------184126686857005263182509
Content-Disposition: form-data; name="notice"; filename="subtype_1_20230614.xml"
<subtype_1_20230614.xml>
----------------------------184126686857005263182509
Content-Disposition: form-data; name="metadata"
{
"noticeAuthorEmail": "eduard.smirnov@mercell.com",
"noticeAuthorLocale": "en"
}
----------------------------184126686857005263182509
Content-Disposition: form-data; name="Ocp-Apim-Subscription-Key"
XXXXXXXXXXXXXXXXXXXXXXXXXX
----------------------------184126686857005263182509--
 
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Request-Context: appId=cid-v1:bccc2562-d0f3-4aee-a8f8-4e3c365ecce0
Date: Wed, 14 Jun 2023 15:35:02 GMT
 
{
"success": false
}`

**File attached is**
`<?xml version="1.0" encoding="utf-8"?>
<PriorInformationNotice xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:efac="http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1" xmlns:efext="http://data.europa.eu/p27/eforms-ubl-extensions/1" xmlns:efbc="http://data.europa.eu/p27/eforms-ubl-extension-basic-components/1" xmlns="urn:oasis:names:specification:ubl:schema:xsd:PriorInformationNotice-2">
  <ext:UBLExtensions>
    <ext:UBLExtension>
      <ext:ExtensionContent>
        <efext:EformsExtension>
          <efbc:TransmissionDate>2023-06-14+00:00</efbc:TransmissionDate>
          <efbc:TransmissionTime>15:14:29+00:00</efbc:TransmissionTime>
          <efac:NoticeSubType>
            <cbc:SubTypeCode listName="notice-subtype">1</cbc:SubTypeCode>
          </efac:NoticeSubType>
          <efac:Organizations>
            <efac:Organization>
              <efac:Company>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="NOR">Buyer 1</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:CityName>Oslo</cbc:CityName>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">NOR</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">b1111</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Telephone>+37212345678</cbc:Telephone>
                  <cbc:ElectronicMail>mail@mail.mm</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
            <efac:Organization>
              <efac:Company>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0002</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="NOR">Buyer 2</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:CityName>Tallinn</cbc:CityName>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">EST</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">b22222</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Telephone>222</cbc:Telephone>
                  <cbc:ElectronicMail>b1@b1.bb</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
            <efac:Organization>
              <efac:Company>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0003</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="NOR">Reviewer 1</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:CityName>Bergen</cbc:CityName>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">NOR</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">r111</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Telephone>+37212345678</cbc:Telephone>
                  <cbc:ElectronicMail>mail@mail.mm</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
          </efac:Organizations>
        </efext:EformsExtension>
      </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>
  <cbc:UBLVersionID>2.3</cbc:UBLVersionID>
  <cbc:CustomizationID>eforms-sdk-1.6#extended#urn:fdc:anskaffelser.no:2023:eforms:eu</cbc:CustomizationID>
  <cbc:ID schemeName="notice-id">34f5affa-7996-48d8-a654-be0a719ed0be</cbc:ID>
  <cbc:IssueDate>2023-06-14+00:00</cbc:IssueDate>
  <cbc:IssueTime>15:14:29+00:00</cbc:IssueTime>
  <cbc:VersionID>01</cbc:VersionID>
  <cbc:RegulatoryDomain>32014L0024</cbc:RegulatoryDomain>
  <cbc:NoticeTypeCode listName="planning">pin-buyer</cbc:NoticeTypeCode>
  <cbc:NoticeLanguageCode>NOR</cbc:NoticeLanguageCode>
  <cac:ContractingParty>
    <cbc:BuyerProfileURI>https://www.ww</cbc:BuyerProfileURI>
    <cac:ContractingPartyType>
      <cbc:PartyTypeCode listName="buyer-legal-type">body-pl-la</cbc:PartyTypeCode>
    </cac:ContractingPartyType>
    <cac:ContractingActivity>
      <cbc:ActivityTypeCode listName="authority-activity">defence</cbc:ActivityTypeCode>
    </cac:ContractingActivity>
    <cac:Party>
      <cac:PartyIdentification>
        <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
      </cac:PartyIdentification>
    </cac:Party>
  </cac:ContractingParty>
  <cac:ContractingParty>
    <cbc:BuyerProfileURI>http://buyer1.xx</cbc:BuyerProfileURI>
    <cac:ContractingPartyType>
      <cbc:PartyTypeCode listName="buyer-legal-type">body-pl-cga</cbc:PartyTypeCode>
    </cac:ContractingPartyType>
    <cac:ContractingActivity>
      <cbc:ActivityTypeCode listName="authority-activity">pub-os</cbc:ActivityTypeCode>
    </cac:ContractingActivity>
    <cac:Party>
      <cac:PartyIdentification>
        <cbc:ID schemeName="organization">ORG-0002</cbc:ID>
      </cac:PartyIdentification>
    </cac:Party>
  </cac:ContractingParty>
  <cac:ContractingParty>
    <cbc:BuyerProfileURI>https://www.ww</cbc:BuyerProfileURI>
    <cac:ContractingPartyType>
      <cbc:PartyTypeCode listName="buyer-legal-type">body-pl-cga</cbc:PartyTypeCode>
    </cac:ContractingPartyType>
    <cac:ContractingActivity>
      <cbc:ActivityTypeCode listName="authority-activity">rcr</cbc:ActivityTypeCode>
    </cac:ContractingActivity>
    <cac:Party>
      <cac:PartyIdentification>
        <cbc:ID schemeName="organization">ORG-0003</cbc:ID>
      </cac:PartyIdentification>
    </cac:Party>
  </cac:ContractingParty>
  <cac:ProcurementProject>
    <cbc:Name languageID="NOR">Main title</cbc:Name>
    <cbc:Description languageID="NOR">Main description</cbc:Description>
    <cbc:ProcurementTypeCode listName="contract-nature">works</cbc:ProcurementTypeCode>
    <cbc:Note languageID="NOR">Some additional information</cbc:Note>
    <cac:MainCommodityClassification>
      <cbc:ItemClassificationCode listName="cpv">45000000</cbc:ItemClassificationCode>
    </cac:MainCommodityClassification>
  </cac:ProcurementProject>
</PriorInformationNotice>`

The request took about a minute to complete.

**Comment by kjorlaug** [comment]
Hi - the validation of the EU rule set is resourceintensive and we are working on options there.

Regarding your file over you are only sending norwegian language, but indicating EU customization that requires at least one EU language to be present. Change the customizationid to national and it should pass.

**Comment by eduardsmirnov** [comment]
@kjorlaug Please re-open the issue!
I like your explanation but it is for a human. How the computer should understand what happened if you return back only this
`{ "success": false }`

**Comment by eduardsmirnov** [comment]
When I send a notice to API and it is not accepted, I want to know what happened to be able first learn from it and maybe even fix "my validator", second to be able to perform some automated action depending on the received response. Right now the only action I can do is to fail a notice and ask a user to call DFO support for clarification cause I have no clue what happened.
