### ISSUE TITLE
Ingen linker til konkurransegrunnlaget i kunngjøring

### ISSUE THREAD

**Issue by JonathanB1234** [anskaffelser/eforms-sdk-nor#80]
Hei, 

Vi har lagt merke til at flere veiledende kunngjøringer inneholder ikke linker til anskaffelsesgrunnlaget, som f.eks.

https://doffin.no/notices/2024-107053

Det står følgende på siden,

"Konkurransedokumenter
Fant ingen dokumenter for denne kunngjøringen. Finn lenken til oppdragsgivers KGV i kunngjøringen."

Men det finnes ingen tilsvarende link i selve kunngjøringsteksten.

**Comment by CharlotteKolle** [comment]
Hei! 

Vi har sjekket kunngjøringen og det ligger ingen informasjon i kunngjøringen om lenke til KGV - derfor klarer vi heller ikke å vise den på Doffin. Dette vil høyst sannsynlig også være tilfelle for øvrige kunngjøringen uten denne informasjonen. Doffin gjør ingen kvalitetssikring av innhold utover å validere etter de tekniske kravene til TED, det er hver enkelt oppdragsgiver som er ansvarlig for at kunngjøringen inneholder relevant informasjon. 

Dette må rettes opp med en endringskunngjøring. I disse tilfellene er det oppdragsgiver som har kunngjort som du må ta kontakt med for å få tilstrekkelig informasjon.
