### ISSUE TITLE
A comma is added at the end of the document URL causes error for suppliers that want to see documents

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#82]
This seems to be a general issue affecting all notices. See for example:
* https://doffin.no/notices/2024-107919
* https://doffin.no/notices/2024-107470
* https://doffin.no/notices/2024-108050

<img width="1381" alt="Screenshot 2024-05-29 at 15 24 43" src="https://github.com/anskaffelser/eforms-sdk-nor/assets/64864592/d56cfab8-cdd6-4af1-8a5a-f1aa25fc7c6b">

We are not sending any comma in XML.

<img width="570" alt="Screenshot 2024-05-29 at 15 28 31" src="https://github.com/anskaffelser/eforms-sdk-nor/assets/64864592/494dd3d5-2f18-45e4-9fdd-d58076491aee">

**Comment by kjorlaug** [comment]
There is a fault in the OPs EFX-framwork concating array of strings adding a comma to the link - we are aware of the problem. This only affects the link in the accordion, not the link highlighted in Doffin.

I'll check the status internally and come with an update here.

**Comment by Colan71** [comment]
Hi,
Any update on this one?

**Comment by kjorlaug** [comment]
No. Waiting for confirmation if this will be resolved when migrating to SDK 1.10

**Comment by kjorlaug** [comment]
We are finally ready to deploy a fix for this into production. It should be updated within a day or two. Thank you for your patience!
