### ISSUE TITLE
Doffin search practically does not work - at least not for advisory notice

### ISSUE THREAD

**Issue by sondresb** [anskaffelser/eforms-sdk-nor#85]
We find it literally impossible to find this notice on Doffin: https://doffin.no/notices/2024-108293 (the only way is to search for absolutely all notices, sort by date and scroll down).

For instance it is not shown searching for any of these terms one by one (single word, the one shown with quotes tried with and without):
Ladeinfrastruktur
Rammeavtale
"Viken Vest Innkjøpssamarbeid"

At one point I was able to finally find it from the complete list and then it seems the search somehow starts working again. Caching? Not considered active until actually loaded?

It is not a one time issue, we have double digit number of sessions trying to figure this out. Top pri from our point of view.

Sondre, CTO at Artifik

**Comment by sondresb** [comment]
It really seems like the active thing is the key. It is not considered active?

**Comment by CharlotteKolle** [comment]
Hi, its in the "planning" phase, not competition - so I find it when I search for all the key words you mentioned. 
We will give it the status "active" if you provide a deadline for the RFI. 
We are planning on making a change to the filters applied automatically when searching and not pre-select "active competition", that might cause less confusion about the phases and statuses.

**Comment by sondresb** [comment]
Yeah, I selected planning when testing the search. We'll revise and send submission deadline then I assume, but as mentioned on email it looks like we are not the only ones having this interpretation/expectation/oversight (EU Supply/Sirdal in 2024-108076 is very likely to consider their RFI as "active" as well).

Also the default sort should really be either by newest first or some weight to show newer higher in the default relevance algo. If I search for "rfi vestre viken", the RFI in question is not in the top 200 in the default search sorting.
