### ISSUE TITLE
/v2/search sortBy ISSUE_DATE_ASC virker ikke lengre

### ISSUE THREAD

**Issue by AudunWA** [anskaffelser/eforms-sdk-nor#86]
Hei, vi er helt avhengig av dette søkeparameteret, men fra kl. 09:00 i går (5. juni) så har ikke dette fungert, og vi har fått 404 med tom body. Eksempelspørring: 
Fungerer: GET https://api.doffin.no/public/v2/search
Fungerer ikke: GET https://api.doffin.no/public/v2/search?sortBy=ISSUE_DATE_ASC

@klakegg @kjorlaug @CharlotteKolle

**Comment by CharlotteKolle** [comment]
Viser til mailinfo sendt ut her og avslutter denne. Det er nå publication date som brukes (også beklager jeg igjen at vi ikke rakk å sende ut info før dette gikk i prod).
