### ISSUE TITLE
We need an update on NOT_PUBLISHED notices

### ISSUE THREAD

**Issue by Colan71** [anskaffelser/eforms-sdk-nor#87]
Hi,

Can you give us an update regarding the notices with several lots that are not getting published? 

Form ID's:
663b2ddccf39f878b289a5f6
666984d6a76168490a35dbad

Kind regards,
Åsa

**Comment by Colan71** [comment]
Hi,
We **really** need an update on these notices so we can inform our customers about the status.
Form ID:
663b2ddccf39f878b289a5f6
666984d6a76168490a35dbad

**Comment by Colan71** [comment]
We have one more case where the notice is not getting published. The Form ID is:
667eba3d555d3c06d7ec0142

Please check why it is not getting published and please give us some feedback on the reason for all the NOT_PUBLISHED cases!

**Comment by kjorlaug** [comment]
We are looking into these. There is an issue of processing them that is puzzeling. Hoping to have a better update within EOB today.

**Comment by Colan71** [comment]
Any update?

**Comment by kjorlaug** [comment]
We pushing a hotfix later today. It would be great if you can resubmit when that is ready - I'll contact you directly.

**Comment by kjorlaug** [comment]
We are ready to recieve re-sumissions of the the three notices now @Colan71 :)

**Comment by Colan71** [comment]
The notices are re-submitted now.

**Comment by Colan71** [comment]
Hi,
The notice with Form ID: 663b2ddccf39f878b289a5f6 is still not published. Please address this a.s.a.p and give us an update!

**Comment by Colan71** [comment]
I see the above mentioned notices are published now! Good!
