### ISSUE TITLE
Question - Below threshold notice (on Production)

### ISSUE THREAD

**Issue by stefan-sluijter-mercell** [anskaffelser/eforms-sdk-nor#88]
Hi! 

A client of us is trying to update a contract in a below threshold notice (N29).
And is getting the following error:

`rules:BT-13716-notice must match the following pattern: AnySectionIdentifier` 

I've checked the rule and the regex is checking the section identifiers for validity.
A `CON` section is not allowed in this change notice.

What form subtype should he use to update a contract on a below threshold notice?

Kind regards,

Stefan Sluijter
(Working for Mercell)

**Comment by kjorlaug** [comment]
The question is if the right thing is a contract modification notices (subtype 40). We currently don't support this on national level (sending one would mean it ends up in TED). Can you email me the notice you are trying to send?

**Comment by kjorlaug** [comment]
Changes to the actual contract (CON-* change reason) requires subtype 40, but since this is correcting the award notice, and not the actual contract, you need to submit a N29 change notice without this element to get it through. Hope this helps :)
