### ISSUE TITLE
Noitce is not published to TED 

### ISSUE THREAD

**Issue by MaxKholoshnyi** [anskaffelser/eforms-sdk-nor#89]
Good morning guys

We have an issue with notice 
cb5965a5-183d-41fa-849c-ae802c2d358b  version 1. 
It is published in DOF but not in TED.
Customer is asking what is the reason, but there is nothing we can tell without your input.
Thanks.

**Comment by MaxKholoshnyi** [comment]
Thanks for quick response. Looking forward for outcome of investigation

**Comment by kjorlaug** [comment]
Fixed - forgot to close...
