### ISSUE TITLE
Why the validation does not allow Norwegian as a main language?

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#9]
Our expected flow was 
1. user creates a notice in Norwegian (the main language)
2. we receive a machine-translated notice from Doffin API where still Norwegian is the main language and additionally English is added
3. we let user review English texts being an additional language
4. we submit a notice with NOR (main) and ENG (additional)

Now it seems that the validation provided in NOR SDK v 1.6 expects English to be the main language of the notice.
"_BT-702(a)-notice must contain a value from codelist eu-official-language_"

With the flow expecting English to be the main language, we must force our users to start a notice in English which is not the behavior Norwegian users want.

What do you think?

**Comment by klakegg** [comment]
Norwegian is not allowed as official language in notices so Norwegian have to be included as an non-official language. The semantics of BT-702 is pretty clear about the use, so including Norwegian for BT-702 would be a breach of the semantics of eForms and the rules governing notices.

How are you handling this for Iceland?
