### ISSUE TITLE
Feilmelding Notices API testmiljø

### ISSUE THREAD

**Issue by kayjohnsen** [anskaffelser/eforms-sdk-nor#91]
Hei, jeg får en feilmelding i testmiljøet mot Notices APIet. 

"Parse Error: There seems to be an invalid character in the response header value"

![image](https://github.com/user-attachments/assets/1fdcf1cb-9d50-4aa1-a6ad-18ef62f48f93)

Tilsvarende kall i produksjon fungerer. Er dette en feil hos meg eller hos dere?

**Comment by kayjohnsen** [comment]
Purrer på denne saken. Har jeg meldt inn til feil kanal? Finnes det type supportkanal man bør melde slikt inn til? Hva er svartiden deres?

**Comment by kjorlaug** [comment]
Hei

Takk for litt tålmodigheit :) Dette er rett kanal. Vi har ingen kjente feil for tida. Gjer meg ei teneste og sjekk med https://betaapi.doffin.no/ som url?

Mvh

Rune

**Comment by kayjohnsen** [comment]
Hei, jeg fikk samme feil mot betaapi.

Men jeg har funnet ut litt mer om hva som "feiler". Jeg får kjørt kall med Postman desktop (det feiler med Postman web). Hvis jeg i Postman desktop slår på "Enable strict HTTP parser", så feiler det på desktop-versjonen også. Videre ser jeg at forskjellen mellom produksjon- og test-APIet deres er at i test, så returnerer dere "Content-Security-Policy":

![image](https://github.com/user-attachments/assets/d5a80aa8-9d0b-4a0b-91d6-073f26429325)

Jeg mistenker at denne inneholder noe som ikke er "gyldig" som response header value, men kan ikke si det sikkert. Feilmeldingen sier "Section=ResponseHeader Detail=CR must be followed by LF".

Jeg har funnet en vei rundt ved å bruke:
` <httpWebRequest useUnsafeHeaderParsing="true" /> `

For min del kan dere lukke saken.
