### ISSUE TITLE
Worng TED publication id

### ISSUE THREAD

**Issue by MaxKholoshnyi** [anskaffelser/eforms-sdk-nor#92]
Good morning
We have a competition chnage notice that have odd TED ID
4f783658-5190-4f2d-9b2a-cac4d0cabf23 version 1

Contract notice (e7cb3353-1d0a-45c2-8803-5eedf09f2285) has correct TED id but competion chnage ID returns some German tender in TED.  Can you guys please have a look.
Thanks

**Comment by kjorlaug** [comment]
TED had a hickup on publishing last Friday (I assume Mercell also recieved an email about this). We have 36 notices with wrong ted id - we are looking into how to update to get the right ones in now.

**Comment by MaxKholoshnyi** [comment]
Thanks a lot. Yeah we discoved as well notices that were sent to TED directly with same issue.
