### ISSUE TITLE
Feil i nedlasting av 2024-113319

### ISSUE THREAD

**Issue by AudunWA** [anskaffelser/eforms-sdk-nor#93]
`GET https://api.doffin.no/public/v2/download/2024-113319` gir følgende respons:

Status 500
```
Cannot invoke "com.fasterxml.jackson.databind.JsonNode.textValue()" because the return value of "com.fasterxml.jackson.databind.node.ObjectNode.get(String)" is null
```

**Comment by SoldierFace** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by haroonalam16** [comment]
Hello,
Sorry for inconvenience, Issue has been fixed now, you can download it. Thanks for your understanding.
Regards,
H. Alam

**Comment by AudunWA** [comment]
Det samme gjelder nå med 2024-114427, 2024-114428, 2024-114429 og 2024-114430. @haroonalam16

**Comment by AudunWA** [comment]
@kjorlaug

**Comment by kjorlaug** [comment]
Då skal kunngjeringane være tilgjengelige

**Comment by AudunWA** [comment]
Supert!
