### ISSUE TITLE
Problemer med issueDateTo i /search

### ISSUE THREAD

**Issue by AudunWA** [anskaffelser/eforms-sdk-nor#96]
Fra i dag tidlig har ikke `issueDateTo`-filteret i `/search`-endepunktet fungert lengre. Merker også at vi får en del timeouts fra API-et. Tipper det kan gjelde `issueDateFrom` m.m. også, uten å ha sjekket.

**Comment by RaghadAL-Abd** [comment]
Hei Audun!
Beklager denne feilen, dette er fikset nå, du kan bruke api-et med `issueDateTo` og `issueDateFrom `.

**Comment by AudunWA** [comment]
Takk for rask fiks, ser ut til å være i orden.
